### ISSUE TITLE
Samson deletes docker image just built

### ISSUE THREAD

**Issue by rata** [zendesk/samson#1043]
Hi,

In app/models/docker_builder_service.rb there is a ```build.docker_image.remove(force: true)``` that is done by default. This makes our docker builds take longer, as there is always no cache but the base image.

Although it seems really on purpose. Can I ask why do you do that? To keep the disk clean on the server? And do your builds always never use the cache, then? Or do you do some other trick to reuse the cache when building images?

We would like to use the cache and clean the disk somehow (probably running some other command to clean daily/weekly/something). Do you think it's an option to not do that if some env var is defined or something?

Thanks!
Rodrigo

**Comment by jonmoter** [comment]
@henders added that logic, so cc'ing him.

I believe the issue that our docker hosts were filling up 'cause we never cleaned up the images.  I get your point that it's nice to have some cached images on disk, especially if you're using the same ones repeatedly.  I've looked into https://github.com/spotify/docker-gc briefly, but haven't tried running it before.

We could add an environment variable that makes it optional whether to delete the images after pushing them. Would that work for you?

**Comment by rata** [comment]
@jonmoter haha, I was looking at the same thing from spotify too! :-D

Yes, that will work I think. Do you want me to do the patch? Or will you do it? :)

**Comment by jonmoter** [comment]
You're welcome to create a PR that adds an ENV var.

**Comment by rata** [comment]
This is already fixed, closing

**Comment by rata** [comment]
@jonmoter @grosser we are using spotify/docker-gc to cleanup the images (run the builder and docker-gc in different containers in a pod, in the docker-gc container I set the variable "DOCKER_HOST" to "tcp://localhost:2375").
I configured it yesterday and seems to be working fine for now. I did some changes (the docker image for docker-gc doesn't build in the spotify repo), you can see them in rata/docker-gc
