### ISSUE TITLE
Kubernetes deployment runs stability test before all pods started

### ISSUE THREAD

**Issue by rata** [zendesk/samson#1051]
Hi,

The kubernetes deployment starts the stability test even if not all replicas are started and, if that happens, it detects the new replicas as a restart and says the deployment failed when in fact it went just fine.

The problem seems to be in plugins/kubernetes/app/models/kubernetes/deploy_executor.rb, inwait_for_deploys_to_finish(). When it does:

```
          if statuses.all?(&:live)
            @output.puts "READY, starting stability test"
            @testing_for_stability = 0
```

It should do something like, IIUC:

```
          if statuses.all?(&:live) && replica_target == replica_live
            @output.puts "READY, starting stability test"
            @testing_for_stability = 0
```

I'm not sure how to get the replica_target and replica_live (it seems from the release_doc, but not sure which one as a release has many).

**Comment by grosser** [comment]
oh yeah, good catch!
I'll try to whip up a patch for that shortly :)

**Comment by rata** [comment]
@grosser oh, great. Thanks!
