### ISSUE TITLE
Enable setting default new user role

### ISSUE THREAD

**Issue by akjones** [zendesk/samson#1184]
We're using github authentication and authorise by restricting our users to a particular group in our organisation. When they first log in, users are assigned the "Viewer" role, and since all our users are trusted (because we've put them in the right group in github), we want them all to have the role "Super admin". Currently someone has elevate permissions for folks manually.

It'd be great to be able to set the default user role that applies to all new users, so we could skip the manual steps.

**Comment by grosser** [comment]
sounds good ... want to make a PR ? :)

**Comment by akjones** [comment]
:) We'll see how we go.
