### ISSUE TITLE
[Docker + MySQL] Unable to save environemnts

### ISSUE THREAD

**Issue by machei** [zendesk/samson#1212]
I tried to save enviroments into specific project, it takes long time then i got error 404. I don't know.

Docker + Mysql External

log:

```
Started PATCH "/projects/example" for 222.222.222.21 at 2016-08-17 02:30:43 +0000
Processing by ProjectsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"XXX", "project"=>{"name"=>"Example", "description"=>"", "owner"=>"", "repository_url"=>"git@git.example.pl:example/example.git", "permalink"=>"example", "release_branch"=>"master", "auto_release_docker_image"=>"0", "environment_variables_attributes"=>{"0"=>{"name"=>"aa", "value"=>"aaa"}}, "environment_variable_group_ids"=>[""]}, "id"=>"xxx"}
```

**Comment by grosser** [comment]
- try reproducing from the console, maybe that shows more details
 - missing 404 / end of logs ... enable request-id tagged logging to see where the request ends / all it's messages
 - does it work when saving non-environment settings ?
 - can you reproduce in development environment ?

**Comment by machei** [comment]
Now all works.
What I have done:
- copied ssh key into instance based on docker ex. `COPY ssh/id_rsa /root/.ssh/`
- replaced Repository URL into valid with prefix : `ssh://`
