### ISSUE TITLE
Commit range assumes GitHub is used

### ISSUE THREAD

**Issue by rchady** [zendesk/samson#1234]
When you set Samson up to use Gitlab, when you review a deploy the commit range that is selected assumes you are using github.  This can be seen in the changeset/files partial where it calls changes.github_url directly.  This also means that even if you aren't using Github, it will try to build a github url using the repository you provide.

Seems like this should be a relatively easy fix?  Just add support for something like changeset.repository_url that just references GitRepository.repository_url instead of calling github_url from the view directly.

**Comment by grosser** [comment]
Sounds good, want to make a PR ?

**Comment by rchady** [comment]
Do you have anything explaining the overall plans for Samson?  For example, do you want the repository type to be per project, or do you plan on it being one type globally?  In general I'd think it would be nice if each project could have its type set with repo information.  Don't want to do any work if it doesn't fit in with the overall plans though.

**Comment by grosser** [comment]
Configuring gitlab and github should allow you to use projects on either
one ... there is some logic in the project to detect which one is used ...
if that does not work then let's simply fix it where needed.

**Comment by grosser** [comment]
fixed by https://github.com/zendesk/samson/pull/3227
