### ISSUE TITLE
Move to open source on Code Climate.

### ISSUE THREAD

**Issue by dragonfax** [zendesk/samson#1427]
You can setup Samson as an open source project in Code Climate to get it off the Zendesk paid account. Code climate is free for public repos. Then just update the README to use the new code climate url.

I don't have admin on this repo, or I'd do it myself

@grosser

**Comment by grosser** [comment]
Tried to, but don't have access to the token ... might be not possible according to webhook docs

`You're trying to set up a service hook for a repository that lives in the Open Source section of your Dashboard. We don't yet support service hooks for these repositories.`

**Comment by dragonfax** [comment]
Lets forget about this for the moment then. Thanks for giving it a try.
