### ISSUE TITLE
redirect_back firing when it shouldn't

### ISSUE THREAD

**Issue by sandlerr** [zendesk/samson#1534]
For example, I get redirected to `github.com` clicking on the samson CI hook in https://github.com/zendesk/zendesk_console/pull/12575 when not logged in

**Comment by grosser** [comment]
I guess we should only redirect to referrer when they are internal or something like that ... are you sure it's redirect_back and not omniauth ?

**Comment by sandlerr** [comment]
Not sure where it came from, could well be omniauth

**Comment by grosser** [comment]
any repro steps that work locally ?

**Comment by sandlerr** [comment]
I'll look at it in a few days, mind keeping the issue open as a reminder?

**Comment by grosser** [comment]
sure :D

**Comment by sandlerr** [comment]
Fixed by #1544 thanks @neroleung !

**Comment by neroleung** [comment]
Urgh.. Didn't even know this issue existed. lol. You're welcome.
