### ISSUE TITLE
How to deploy using Elastic BeanStalk to AWS and track it here?

### ISSUE THREAD

**Issue by dashbitla** [zendesk/samson#1571]
How to deploy using Elastic BeanStalk to AWS and track it here?

Or does it work only with Capistrano?

**Comment by grosser** [comment]
install aws cli tools and then deploy with them ?

**Comment by dashbitla** [comment]
We use AWS EBS for deploying the applications.
How to track it under Samson? Is it possible to do the same using Samson tool?
Any examples?

**Comment by grosser** [comment]
We use aws cli to deploy from samson ... that will produce logs / show what was deployed, but not show the 'current' state since it does not talk to aws all the time.
Alternatively you could use some aws client and hit the the api directly to do deploys.
There is no direct EBS integration.

**Comment by dashbitla** [comment]
Thank you.
Will try it out. Any example scripts or procedural steps on how its configured?

**Comment by grosser** [comment]
Just follow EBS cli instructions ... it's exactly the same ... only
difference is that the config (.elasticbeanstalk) is not persisted between
deploys.

**Comment by jonmoter** [comment]
Samson just runs a bunch of shell commands, and saves the output. So anything you can do in a shell, you could theoretically do via Samson.

If you want to deploy to AWS, you'll probably want to install the [AWS CLI](https://aws.amazon.com/cli/) on the host that is running Samson. Once that's installed, you can use it in a deploy script.  So you could run `aws elasticbeanstalk create-environment ...` in a stage.

Or you could write a deploy script in the language of your choice (bash, ruby, python, perl, etc.) check that script into your github repo, and then have Samson execute that script.

For injecting secrets, like the AWS credentials, you may want to use the secrets module, and then have lines like this in your stage:

```
export AWS_ACCESS_KEY_ID="secret://my_aws_access_key_id"
export AWS_SECRET_ACCESS_KEY="secret://my_aws_access_key_secret"
```

**Comment by dashbitla** [comment]
Thank you! That helps.
