### ISSUE TITLE
DEMO Deployment 

### ISSUE THREAD

**Issue by attahkhan016** [zendesk/samson#1586]
Hello Sir ,
I am a freshmen to this Samson , I  wasn’t able to deploy a sample project with samson to have a look and feel of this open source tool . can you please guide me for a sample deployment of samson ?
When I tried the demo , its showing   "You are not authorized to view this page" can you walk me through how to use it so that I could evaluate it for our company use .

**Comment by grosser** [comment]
The demo at https://samson-demo.herokuapp.com/ has a big 'signin with github' button.

If you follow the [Getting started](https://github.com/zendesk/samson/blob/master/docs/setup.md) docs you should get a local version running that has github auth too.

For any other auth option see [.env.example](https://github.com/zendesk/samson/blob/master/.env.example)

**Comment by attahkhan016** [comment]
Hello Sir , thank you for the links and i could go this far
![screenshot from 2016-12-28 16-59-26](https://cloud.githubusercontent.com/assets/20012535/21521033/1d4fcd3c-cd1f-11e6-9a44-c0aaca11c735.png)
can  you help resolve this to have a sample deployment ?
I made a sample mysql server in aws rds and attached it , can you help me move further ?

**Comment by grosser** [comment]
that `rake should not be loaded` is weird ... I'll take a look ... for now
you can just comment out that line from initializers/zz_boot_speed_
test.rb:10

**Comment by grosser** [comment]
opened PR to fix ... hope all is well now!
If you know how to improve the docs / how this would have been easier, please open a docs PR or let me know ... recently reworked a lot of docs ...

**Comment by grosser** [comment]
If you login then you should be the first user and get super-user access ...
try `rails c` + `User.count` ... should be 1 ... then `User.first.update_column(:role_id, 3)` to give it super-user if it did not have that ... could also be that github auth failed ... then start with the .env.bootstrap and check that this works
