### ISSUE TITLE
can't create new project after update version v1211

### ISSUE THREAD

**Issue by easylo** [zendesk/samson#1600]
30/12/2016 12:22:30Started GET "/projects/new" for 10.42.50.206 at 2016-12-30 11:22:30 +0000
30/12/2016 12:22:30Processing by ProjectsController#new as HTML
30/12/2016 12:22:30  Rendering projects/new.html.erb within layouts/application
30/12/2016 12:22:30  Rendered shared/_errors.html.erb (0.2ms)
30/12/2016 12:22:30  Rendered projects/_form.html.erb (23.7ms)
30/12/2016 12:22:30  Rendered projects/new.html.erb within layouts/application (24.5ms)
30/12/2016 12:22:30Completed 500 Internal Server Error in 62ms (ActiveRecord: 0.0ms)
30/12/2016 12:22:30
30/12/2016 12:22:30ActionView::Template::Error (undefined method `release_source' for #<Project:0x007fc3dcfd8f20>
30/12/2016 12:22:30Did you mean?  releases):
30/12/2016 12:22:30     9:     <%= form.input :permalink, required: true if project.persisted? %>
30/12/2016 12:22:30    10:     <%= form.input :release_branch, help: 'New commits on this branch will cause a release when a webhook arrives.' %>
30/12/2016 12:22:30    11:     <%= form.input :release_source, help: 'Selects which type of webhook will create a release' do %>
30/12/2016 12:22:30    12:       <%= form.collection_select :release_source, webhook_sources_for_select(Samson::Integration::SOURCES, none: true), :second, :first, {}, class: "form-control" %>
30/12/2016 12:22:30    13:     <% end %>
30/12/2016 12:22:30    14:     <% if ENV['DOCKER_FEATURE'] %>
30/12/2016 12:22:30    15:       <%= form.input :docker_release_branch, help: 'New commits on this branch will cause a docker image to be built when a webhook arrives.' %>
30/12/2016 12:22:30
30/12/2016 12:22:30app/views/projects/_form.html.erb:12:in `block (2 levels) in _app_views_projects__form_html_erb___3399883129209708539_70239504028020'
30/12/2016 12:22:30lib/samson/form_builder.rb:64:in `content_tag'
30/12/2016 12:22:30lib/samson/form_builder.rb:33:in `block in input'
30/12/2016 12:22:30lib/samson/form_builder.rb:64:in `content_tag'
30/12/2016 12:22:30lib/samson/form_builder.rb:23:in `input'
30/12/2016 12:22:30app/views/projects/_form.html.erb:11:in `block in _app_views_projects__form_html_erb___3399883129209708539_70239504028020'
30/12/2016 12:22:30app/views/projects/_form.html.erb:1:in `_app_views_projects__form_html_erb___3399883129209708539_70239504028020'
30/12/2016 12:22:30app/views/projects/new.html.erb:4:in `_app_views_projects_new_html_erb___4389364194593175237_70238218849500'
30/12/2016 12:22:30app/controllers/concerns/current_user.rb:32:in `block in login_user'
30/12/2016 12:22:30config/initializers/paper_trail.rb:17:in `with_whodunnit_user'
30/12/2016 12:22:30app/controllers/concerns/current_user.rb:32:in `login_user'

**Comment by easylo** [comment]
it is possible to edit a project but not to create one new.

the message speak : https://github.com/zendesk/samson/blob/master/app/views/projects/_form.html.erb#L12

forgotten an option for form.collection_select ?

**Comment by grosser** [comment]
Before deploying a new version you have to run migrations so new columns like release_source get added to the database.

`bundle exec rake db:migrate`
