### ISSUE TITLE
Rename Webhooks?

### ISSUE THREAD

**Issue by mariovisic** [zendesk/samson#1654]
Hi guys

Currently the way the slack webhooks plugin works with pending deploys isn't ideal. When the `Before Deploy` hook fires jobs are actually always in the "pending" state and so you get a message that says "Mario is about to deploy v7063 to Production".

Sometimes that means that the deploy will start shortly and other times it means that the deploy is queued behind another one, so you can sometimes get a string of queued deploys and the slack output is all muddled up.

Another issue is that when calculating what pull requests will be deployed, if there are queued deploys then the same pull request will be shown to be deployed multiple times.

We should be able to address this by adding another hook to the plugin to allow events on the "After Deploy Setup" hook, at this stage the deploy job is actually running, which is what we want. The issue with this is that the UI is going to get REALLY confusing, see here:

<img width="650" alt="options" src="https://cloud.githubusercontent.com/assets/112153/21836774/cb10bc22-d81b-11e6-9e39-bb16b181ba9b.png">

If we now add another hook so we have "Before Deploy" and "After Deploy Setup" as options, it's not immediately obvious that the first is when they get queued and the second is when the deploy job starts.

I think it might make sense to rename the hooks, so change:

`before_deploy` => `deploy_queued`
`after_deploy_setup` => `deploy_started`

That way, using those same labels on the UI will be much more clear having "Deploy Queued" and "Deploy Started" as options would make much more sense.

We'd need to write some data migrations is the downside of this change, as the slack plugin at least (probably others) store them in the database. In that case it could be as simple as adding the extra option for `after_deploy_setup` and changing the labels on the UI to read as queued/started.

Thoughts?

**Comment by grosser** [comment]
I'd opt for moving before_deploy into the jobexecution, so it does what it says ... this existed before we had job queuing, so it was never meant to trigger on pending deploys.

**Comment by mariovisic** [comment]
That could definitely work, would moving the firing of the hook to here make sense: https://github.com/zendesk/samson/blob/2705e61e/app/models/job_execution.rb#L100

The `after_deploy_setup` hook is sent within that method as well but a bit later.

**Comment by mariovisic** [comment]
Actually, at the very top of that method might make more sense, then the job will still be in the pending state rather than running.

**Comment by grosser** [comment]
sounds good!

**Comment by mariovisic** [comment]
Implemented over at https://github.com/zendesk/samson/pull/1664
