### ISSUE TITLE
Feature proposal: Skip Scheduled Builds

### ISSUE THREAD

**Issue by mariovisic** [zendesk/samson#1695]
Our CI tool buildkite has a really neat feature with queued builds, the checkbox is:

#### Skip Scheduled Builds:
> When a new build is triggered, any scheduled builds on that same branch will be automatically skipped. Builds that are already running won't be skipped.

This is really useful especially for staging environments where you don't want to run through all of the queued deploys to get the latest code on there, simply the last one.

I don't think samson currently has a "skipped" status but we could either create this or re-use the cancelled state, although I think it might be more obvious what's happening if we use skipped.

Thoughts?

**Comment by grosser** [comment]
Canceling queued deploys sounds fine ... just don't cancel running deploys :)
... "cancelled" is just fine as long as it says `cancelled by Travis` ... 

Implementation could look like:
 - find pending deploys to the same stage, by `me` (travis user)
 - `JobQueue#dequeue` them
 - mark them as cancelled

Should be opt-in:
 - only slow or frequently changed projects will need this 
 - it's a valid usecase to want 'atomic' deploys

**Comment by mariovisic** [comment]
PR is over here: https://github.com/zendesk/samson/pull/1698
