### ISSUE TITLE
Trouble understanding the shell used to run scripts

### ISSUE THREAD

**Issue by unamashana** [zendesk/samson#1719]
Hello! 

Great work on Samson. Thank you!

I was able to set it up on a DO instance and get it to work. However I am having some trouble with the sh shell that is used to execute commands. For example, I cannot seem to setup ``RBENV_VERSION`` using an export like ``export RBENV_VERSION=1.9.3-p448``. If I do, it looks like when the next command is executed, the export is forgotten

```
» export RBENV_VERSION=1.9.3-p484
» ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

Same way, I have setup agent forwarding for the shell using ~/.profile (and verified it) but I still have to setup agent forwarding as part of the script too. So in essence, I am able to make  it work only as

```
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
echo "$SSH_AUTH_SOCK"
RBENV_VERSION=1.9.3-p448 rbenv exec bundle install --deployment 
RBENV_VERSION=1.9.3-p448 rbenv exec bundle exec cap staging deploy
```

Am I missing something or is this how Samson is supposed to work?

**Comment by unamashana** [comment]
I also noticed that the environment variables set up Samson don't persist either

```
» export REFERENCE=master
» export REVISION=91995344b6fa9429538963660da119611892750f
» export TAG=91995344b6fa9429538963660da119611892750f
» export CACHE_DIR=/home/rails/apps/samson/cached_repos/5627ac37fb24fc4cafd779777d862a59/artifacts
» export STAGE=staging
```

```
» RBENV_VERSION=1.9.3-p448 rbenv exec bundle exec cap $(STAGE) deploy
sh: 37: STAGE: not found
```

**Comment by jonmoter** [comment]
Samson does not pass all of the environment variables it has to the scripts that are run as part of a deploy.  So in a normal user shell, you probably have the `SSH_AUTH_SOCK` environment variable set. But that doesn't get passed into the shell that Samson forks to do your deploy.

Hint, add the line `env | sort` as a line in your deploy script, so you can see all the environment variables that are set.  You might also try executing `which ruby` in both your user shell and in a samson deploy to see if they're the same or different.

Regarding your last comment, you have a typo in your command.  You should say:

```
» RBENV_VERSION=1.9.3-p448 rbenv exec bundle exec cap ${STAGE} deploy
```

Note the curly brackets around `STAGE`.  If you use regular parentheses, the shell is trying to execute a command called `STAGE`, and it's complaining that command doesn't exist.

**Comment by grosser** [comment]
you can set ENV_WHITELIST=SSH_AUTH_SOCK,FOO_BAR to pass along more
variables that you think are safe to be used by the deploy script.

The reason samson does not pass all env vars is that we don't want to
expose samsons secrets (AWS_ACCESS_KEY_ID etc things) to every deploy
script.

**Comment by unamashana** [comment]
@grosser @jonmoter Thank you so much. That helped me understand and solve my issues. Once again, thank you for your work on Samson. You can close this issue.

**Comment by grosser** [comment]
If you find a docs part where you would have found this info, please open a PR :)
