### ISSUE TITLE
"This deploy is queued" message even if queue is empty

### ISSUE THREAD

**Issue by mirago** [zendesk/samson#1891]
Hi, we have an issue where one of our projects always get queued and we see this message. 
```
This deploy is queued, it will be started when previous deploys have finished.
```
However, I see this message even if the queue is empty and there are no other projects currently being deployed.  I click cancel and redeploy and then it usually works, or sometimes I have to cancel it twice.. I now ticked 'can be deployed in parallel' as a workaround, but would like to have more information why is this happening. Any ideas how to debug this? Thanks.

**Comment by grosser** [comment]
Does the message still appear after a page reload ?
Can you reproduce it locally ?

**Comment by mirago** [comment]
I will try to reproduce it locally. Message does indeed still appear after reload. It only disappears if we cancel deployment. Or if we delete samson pod in kubernetes so it restarts..

**Comment by mirago** [comment]
Hi, just fyi I was never able to reproduce it locally. And we did not have this issue since I posted this. So I guess you can close it, will let you know if I have any more info in the future.

**Comment by grosser** [comment]
thx for reporting back :D
