### ISSUE TITLE
memcached configuration

### ISSUE THREAD

**Issue by emdupp** [zendesk/samson#1915]
Hello,

I am running samson in docker-compose and I would like to use a dedicated docker container with memcached.
How can I configure samson to use that instead of trying to connect to memcached locally on 127.0.0.1:11211?
I did not see anything regarding this in the docs.

**Comment by grosser** [comment]
use MEMCACHIER_SERVERS ... see https://github.com/zendesk/samson/blob/master/config/application.rb#L66-L75 .. does that help ?
