### ISSUE TITLE
`Validation failed: Repository url is not valid or accessible` when running script/bootstrap

### ISSUE THREAD

**Issue by danlars** [zendesk/samson#2014]
Hi, just tried to setup a new samson project, here's what i have done so far.
My current environment is `development`, running on localhost(Couldn't get the docker image up an running, __fails with undefined method `marked_for_destrution?`__).
I'm using ssh to connect to GitHub. When running the command `ssh -T git@github.com` i get __Hi danlars! You've successfully authenticated__
I've setup a `GITHUB_TOKEN` and `SECRET_TOKEN` in the .env file.
Am i missing something? I'm no Ruby guru, so i'm not sure where to go from here.

**Comment by danlars** [comment]
Fixed my issue, by authenticating with https instead.

**Comment by grosser** [comment]
what command did you use to start the docker image ?
... last time I checked it worked ... maybe we need to fix some docs ...

**Comment by danlars** [comment]
@grosser In the [Getting Started](https://github.com/zendesk/samson/blob/master/docs/setup.md) documentation, it says that i can just run `docker-compose up` i assumed i could do that without configuring anything. Still doesn't work for me though.

**Comment by grosser** [comment]
fixed in https://github.com/zendesk/samson/pull/2049
