### ISSUE TITLE
Project administrator can't delete projects

### ISSUE THREAD

**Issue by danlars** [zendesk/samson#2082]
When trying to delete a project as project administrator, i get this.
![image](https://user-images.githubusercontent.com/16097615/27275187-a41b200c-54d6-11e7-9bb6-336ceeae2157.png)

 And this in the log.
`ActionController::RoutingError (No route matches [DELETE] "/projects/samson-deployment-test"):`

A quick look in the **routes.rb** file shows that `destroy` is excluded from the route. When removing that exclusion, deleting projects works.

Would like to know, if this is a bug, that has been overlooked?

**Comment by grosser** [comment]
yep, bug introduced when merging the 2 project controllers :)
fix coming

**Comment by grosser** [comment]
https://github.com/zendesk/samson/pull/2084
