### ISSUE TITLE
Word 'deleted' in links

### ISSUE THREAD

**Issue by ilkkao** [zendesk/samson#2094]
I mistakenly deleted a project but thanks to `soft_deletion` gem, I was able to bring it back.

Everything is working like before except the URLs, they are now 

`https://samson.com/my_project/stages/docker-build-deleted-1497513932`

`deleted` part is not optional. Links don't work without it. Could it be removed?

**Comment by grosser** [comment]
Ah yes, on undelete we should remove the `deleted` addition to the
permalink.
Do you want to make a PR for that ?

**Comment by ilkkao** [comment]
If I have understood correctly, this is trickier to fix than I thought. Permalink values get updated in the db during deletion. As there's no UI for undelete, not sure where the deleted part could be removed.

Now I see that permalinks can be edited in the settings. Accidental deletion is pretty rare so it might be enough that fixing is possible via UI manually.

**Comment by grosser** [comment]
true, hope it's not a common workflow :D
