### ISSUE TITLE
Admin permissions

### ISSUE THREAD

**Issue by vitxd** [zendesk/samson#2103]
Hello,

in your documentation it is said that the first user logging in automatically gets super admin permissions.

Unfortunately this is not true and I struggled a lot in order to get full permissions (I inserted some lines in some mysql database, definitely not the right way.)
Is there anything I'm doing wrong or there is a bug somewhere? 

Thanks for the product though, is great!
Vittorio

**Comment by grosser** [comment]
Merged a patch to ignore the seed user ... Can you reproduce the issue on
master  ?

**Comment by grosser** [comment]
... just merged ... https://github.com/zendesk/samson/pull/2087

**Comment by grosser** [comment]
if the error still exists @yizhang-zen will gladly help out ;)

**Comment by vitxd** [comment]
Yes, I can confirm now the first user logging in is granted admin privileges. Thanks!
