### ISSUE TITLE
Boot samson as a service

### ISSUE THREAD

**Issue by vitxd** [zendesk/samson#2109]
Hello again,
I was wondering if there was a standard way to run samson at boot, maybe with systemd... running bundle exec rails s -d will only run puma without the actual application...

Thanks
Vittorio

**Comment by grosser** [comment]
we run `bundle exec puma -c config/puma.rb --restart-cmd 'bundle exec puma -c config/puma.rb'`

**Comment by vitxd** [comment]
That gives me an error:
```
/home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/cli.rb:47:in `initialize': ambiguous option: -c (OptionParser::AmbiguousOption)
        from /home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/bin/puma:8:in `new'
        from /home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/bin/puma:8:in `<top (required)>'
        from /home/samson/.rvm/gems/ruby-2.3.3/bin/puma:22:in `load'
        from /home/samson/.rvm/gems/ruby-2.3.3/bin/puma:22:in `<main>'
        from /home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
        from /home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

```

Also, if I restart the server will this command re start samson?

**Comment by vitxd** [comment]
Ok fixed it. the parameter is actually -C (capital C) and adding -d to the command it will demonize it. not sure about restart on reboot (I'm almost sure it won't)

Thanks!
