### ISSUE TITLE
No error surfaced when project role change fails for user

### ISSUE THREAD

**Issue by cvgw** [zendesk/samson#2190]
On the `projects/PROJECT_NAME/user_project_roles` page,
no error message is raised when the request to change a user's role fails.

Repro:
* Observe network traffic
* Login as user without admin rights to project
* Navigate to user roles page for project
* Change role of user by selecting inactive option from radio buttons
* Observe network request fails and no error is surfaced on the client side

**Comment by grosser** [comment]
thx for so neatly reporting the issue! :)
... atm it shows a `red` failure indicator ... maybe a little to subtle ...

**Comment by grosser** [comment]
![screen shot 2017-08-15 at 2 26 17 pm](https://user-images.githubusercontent.com/11367/29337346-cb03f452-81c5-11e7-9643-4d08cc63976e.png)

**Comment by cvgw** [comment]
Gotcha, I see it now. Didn't notice before. The new color should be perfect :+1:
