### ISSUE TITLE
view projects by deploy group

### ISSUE THREAD

**Issue by jdoconnor** [zendesk/samson#2297]
We have a mapping between k8s namespace and deploy group, and would like to have a view that is closer to representing a namespace. 

(reason why this matters to us) -- our staging environments are differentiated by k8s namespaces. 

I'm happy to do this work, but wanted to run this past your team in case it is completely against the spirit of the project.

either
```
/projects?view_deploy_group=true # ugly, and non-restful, but less confusing with the current /deploy_groups being an admin view 
```
or 
```
/deploy_groups/projects
```

**Comment by grosser** [comment]
we run a similar setup.

not sure what exactly you expect to see on this view ... deploy_groups/123 will show all projects that deploy there ... so how is what you want different ?

**Comment by jdoconnor** [comment]
Maybe i'm not up-to-date enough... When i see that, I see a deploy history list

**Comment by jdoconnor** [comment]
yep... just looked at master. This works. Thanks!
