### ISSUE TITLE
Feature Request: Deploy an open pull request 

### ISSUE THREAD

**Issue by thegeorgeous** [zendesk/samson#2299]
My workflow involves running integration tests on a pull request before it is merged. Sometimes that would also include a demo. Samson doesn't seem to have a system where a pull request can be deployed.

Currently I circumvent this restriction by deploying the branch involved in the pull request. This becomes impossible for projects where I use a 'upstream-fork' workflow and the branch does not exist on the project itself.

**Comment by grosser** [comment]
- for regular PR: you can make github deploy to samson on push with a webhook that has an `any branch` value (leaving branch empty)
 - for forked project: origin repo could notify samson on PR ... then we could add some samson logic to somehow use the forked repo as source ... but that might get ugly/complicated ... I think github creates a fake `theoretical merge commit` ... so look in the webhook payload github sends  for that and we could use it to deploy
