### ISSUE TITLE
Cannot configure SMTP settings in Docker deployment

### ISSUE THREAD

**Issue by elblivion** [zendesk/samson#2327]
Hi Samson team,

We are deploying Samson in Kubernetes using the official image. I have just realised that in this scenario Samson is unable to send emails, e.g. an attempt to Bypass a Buddy Check results in:

```
[06:40:29] JobExecution failed: Connection refused - connect(2) for "localhost" port 25
```

I've looked but there seem to be no environment vars that would allow us to configure the SMTP service without modifying code. What would you recommend in this situation?

We could use a sidecar SMTP container as a workaround, but that's extra hassle. I'm not too proficient with Rails, but presumably tweaking https://github.com/zendesk/samson/blob/master/config/initializers/smtp.rb to make some additional `smtp_settings` configurable by ENV, would that be the preferred way?

Thanks,
Anthony

**Comment by grosser** [comment]
basically https://coderwall.com/p/0sxmrw/rails-actionmailer-smtp-settings-with-environment-variables but with a single `SMTP_URL` would be nice ... then URI.parse that and extract user/pass/host/port ... but leave a nice default so it keeps working for others

**Comment by elblivion** [comment]
A single `SMTP_URL` for me is a bit of an anti-pattern because in our case it would oblige us to store the whole thing as a Secret because credentials. Does a `SMTP_URL` plus optional `SMTP_USER` & `SMTP_PASSWORD` sound OK?

**Comment by grosser** [comment]
yeah kinda makes sense ... so basically:

```
uri = URI.parse(URL)
url.user ||= USER
url.password ||= PASSWORD
```
