### ISSUE TITLE
Samson plugin architecture

### ISSUE THREAD

**Issue by fneves** [zendesk/samson#234]
Samson is growing and the demand for integrations with other applications is growing with it. 
To keep the Samson evolving, and allow all these integration,s it makes sense to think of a plugin infrastructure that would allow any developer to add a piece of functionality/integration into several parts of the Samson workflow.

At the moment Samson is tightly coupled with Git/Github, Flowdock, New Relic, Datadog. 
All these could be extracted into a separate and self configurable plugin that then could be selected on the UI to be part of our instance.

I am going to drop a few ideas how this could work:

 - We would develop a gem with a set of classes that would compose the different plugin types that we could support. This gem would grant some helper methods and rake tasks. This gem should be included on every single plugin that anyone could develop. The Gemfile of this gem would lock the gem versions to match the ones we are using on Samson.

- A plugin could be a Rails Engine. It should live in some kind of repository and downloaded when selected. The download would occur to a specific plugins directory.

- There should be a page where we could list and select all the available plugins for Samson.

- A Samson entity, lets call it PluginRegistry, would keep all the information on Samson about the plugins that are active, and their main requirements (like does it need any config, etc...). When a plugin is selected, we clone their repository/download the gem into that plugins directory.

- When Samson is restarted, we install the dependencies of the plugins and load them.

- There would be placeholders (IFrames) in several extension points of Samson. As an example, we could have an IFrame for the Flowdock plugin in the stage config menu, that would call the config endpoint of the Flowdock plugin and render the config page.

- A plugin that would need some configuration should have a config endpoint following a namespaced convention. ex: /plugins/plugin_name/stage_config or /plugins/plugin_name/global_config

- The plugin UI could also work using the same idea. There would be extension points in several parts of Samson that would load an IFrame for a given plugin and render its UI. The place were that UI would show up would depend on the type of the plugin. The UI plugin endpoint should also follow a naming convention ex: /plugins/plugin_name/ui

I am sure there are a lot of other approaches that would work for a plugin infrastructure, such as  developing a ruby DSL that could configure Samson extensions instead of a Rails Engine. The main point here is, we should discuss and pick the most appropriate one and implement it, so that developing extensions and integrations would not bloat Samson's core code.

**Comment by zendesk-shender** [comment]
I like the idea of a plugin framework, as other people might have an easier time contributing to the project if their code is isolated with known interface points.

A samson-plugin-gem could contain generators to create skeleton plugin projects much like our own app-framework toolkit does.

The more user-friendly extendable apps out there maintain a plugin listing that users can choose from and install. So having a plugin-manager page in Samson would be nice for listing installed plugins + versions, and allow to download/update plugins. This however would require constant maintenance to keep this listing up-to-date. Maybe we rely on them to post their plugin in Rubygems and write a script to pull all Samson compatible gems by reading the gemspec? 

Containing any visual elements of a plugin inside an IFrame is good practice and stops it interfering too much with the core app.

I see 2 approaches to the plugin structure:
- We could either keep all the plugin functionality on the frontend, allowing it access to only the Samson APIs if it needs them, so plugins become mostly Javascript with HTML/CSS templates. A Samson plugin controller could provide plugin-specific functionality like get/set config, etc...
- Allow a hybrid approach, where if a plugin doesn't need any UI, then they just have some Ruby code that has callbacks for Samson events (e.g. deploy success/fails, new projects, new stages, etc...), or both. 
For simplicity we could do the Javascript/HTML approach, and for any events we support, we just have to provide a mechanism to notify them via an emitted event on the javascript side, again, very like our app-framework model.

As Fabio suggested, IFrame location hooks can be scattered through Samson, e.g.:
- Project and Stage configuration screens can append any plugins that implement the PROJECT_CONFIG and STAGE_CONFIG hooks.
- Deploy screen, where they can append UIs below the Deploy button if they implement this hook.

**Comment by jonmoter** [comment]
Do you have some examples of functionality you would like to see added via a plugins architecture?

I like to have a few use cases in mind when coming up with an architecture for something like this, so that we can be sure to come up with an architecture that would support them.

**Comment by fneves** [comment]
Version Control System - Theoretically Samson should be able to support any VCS. It would be nice to support Mercurial, or going even more specific, support Bitbucket the same way we support Github.

Dashboard - Allow a developer to add a custom panel into the dashboard.

Before Deployment - Allow a hook for someone that needs to notify or show any additional information before a deployment starts. Ex: Flowdock buddy request

After Deployment  - We should be able to hook in some kind o plugin that can for example send notifications about the status of the deployment. Ex: Send email informing deployment was successful, something that can analyse the logs of the execution 

I am sure there can be more, but these are probably the easiest to identify and they are a good base to start with.

**Comment by fneves** [comment]
I have a prototype for a WebPlugin almost ready.

The way a plugin looks is kinda like this

```ruby
require 'flowdock_plugin/version'
require 'flowdock_plugin/refinements/models'

module Plugins
  class FlowdockPlugin
    include SamsonSdk::Plugins::WebPlugin
    hook :show_deploy

    stage_config_ui_endpoint do
      render text: 'This will be the place holder for the plugin! in FlowdockPlugin'
    end

    ui_endpoint do
      @deploy = Deploy.find(params[:deploy_id])
      render :ui
    end

    endpoint :get, :some_stuff do
      render text: 'This is a random endpoint'
    end

  end
end
```

Currently it dynamically generates rails controllers, actions and routes. 
I can also render erb templates from within a plugin.
Plugins will be gems that include a SamsonSDK gem that is the glue between Samson and plugins.
I have a branch of my own in Samson, where I have a hook ``` :show_deploy``` that will make a placeholder show up in the deploy screen when waiting for a buddy.

I am trying to port the functionality of Flowdock Integration using this plugin.
I expect to put my code online today (SamsonSDK gem and Samson branch), so that everybody can track the progress and give their own opinions.

**Comment by fneves** [comment]
I've pushed the gem samson_sdk [here](https://github.com/zendesk/samson_sdk) and my branch to Samson (fneves/plugins_architecture). 
If you need a plugin to test have a look, inside examples of SamsonSDK there is also a prototype for the Flowdock plugin.
Remember this is very early development, and a lot of stuff still needs to be cleaned up .

**Comment by grosser** [comment]
closing this for now, if the current setup does not work out or we want to improve it / make it less hacky, we can open a new issue
