### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by brunobatista** [zendesk/samson#236]
Samson works with github? Thanks.

**Comment by jwswj** [comment]
Samson doesn't have Gitlab support at the moment. Feel free to contribute it.

**Comment by brunobatista** [comment]
Thanks @jwswj :+1:

**Comment by cmckni3** [comment]
Sorry to revive a closed issue.

Is this something y'all would allow in the codebase? I asked about support for other Git hosting solutions on the shipit project and they refused to support it to keep the codebase clean.

**Comment by jwswj** [comment]
Yep - would be happy to see Bitbucket & Gitlab support

**Comment by cmckni3** [comment]
@jwswj Awesome :+1:

**Comment by sandlerr** [comment]
https://github.com/zendesk/samson/pull/351 would be an excellent starting point for anyone considering this.
