### ISSUE TITLE
Local GIT repository

### ISSUE THREAD

**Issue by defender** [zendesk/samson#256]
Hi

We are not using Github but local git repository based on attlasian Stash. 
What should be done from my side to make it work

Thanks,

**Comment by grosser** [comment]
should be possible, just have to change a few places and add some ENV flag that disables the github specific features, might even be possible with some added logic like "when path is local don't do github foobar"

**Comment by defender** [comment]
Thanks grosser

Can you please write down step by step  instructions 

Thanks again

**Comment by grosser** [comment]
I'd start with just using a local repo and seeing what breaks and then disabling that feature if it's not critical or fixing it with a `if url.include?('github.com') ... original code else local code`

**Comment by geshan** [comment]
what about private gitlab?

**Comment by jwswj** [comment]
Samson could be made to work with any Git based service with a little work. It would be great to see someone contribute a pull request for Stash, Bitbucket or Gitlab.

**Comment by geshan** [comment]
thanks.
