### ISSUE TITLE
Favorite stars are inconsistent

### ISSUE THREAD

**Issue by AlexRobinson-** [zendesk/samson#2655]
### Description
I believe this PR introduced some inconsistencies with favorited stars which caused me a small amount of confusion when favoriting a project recently.

> make starred and non-starred easy to see
> https://github.com/zendesk/samson/pull/1896

In the dropdown, a black star means favorited. Here is a snippet of that
![image](https://user-images.githubusercontent.com/4470300/37573203-78307eaa-2b69-11e8-84d0-6a2e140b7feb.png)

Then here is the heading for the project page, where a black star means not favorited
![image](https://user-images.githubusercontent.com/4470300/37573276-315f0c2a-2b6a-11e8-9c4e-ca8c14d4b139.png)

and a gold star for favorited
![image](https://user-images.githubusercontent.com/4470300/37573272-27693aec-2b6a-11e8-8687-4ca958a87746.png)

### What should be changed?
The coloring here should be consistent. Either we use a gold star in the drop down as well, or introduce a new _non-favorited_ star for the project page - I saw it was originally a non-filled in star but it could be anything.

E.g.
![image](https://user-images.githubusercontent.com/4470300/37573263-143e7e96-2b6a-11e8-8923-5b8ae922f412.png)

**Comment by grosser** [comment]
@ragurney can you take this on ?

**Comment by ragurney** [comment]
#2656
