### ISSUE TITLE
Buddy check flag meaning changed for some values

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#2707]
When migrating from an older version of Samson, the buddy check got reenabled by accident. The setting in the config file was `BUDDY_CHECK_FEATURE=0`, which matches the current default `BUDDY_CHECK_FEATURE=1` (https://github.com/zendesk/samson/blob/82f72d32a6904669ab761348b620e3cdfceeca67/.env.example#L68)

But this is very non-intuitive - "1" is the default, but anything other than "false" turns it on. I propose adding "0" to the "disabled" values.

**Comment by grosser** [comment]
feel free to open a PR to change it, ideally we should have a helper for this Samson::EnvCheck.truthy? 'BUDDY_CHECK_FEATURE'
