### ISSUE TITLE
Default reference for a stage

### ISSUE THREAD

**Issue by nogates** [zendesk/samson#2745]
Hi there,

I was thinking in implementing a feature so a stage can have a default reference, different from master.

The use case of this feature is that we currently have a `staging` stage, that always deploys the code from the `staging` branch, as opposed from the `production` deploy, which deploys from the `master` branch, in some projects, automatically, in others manually.

In the latter ones, we can check the `Disable reference selection`, so it automatically pick ups the `master` branch, but for the others, we always have to type `staging` in the reference box

It would be awesome if the stages could have an persistent attribute (`default_reference`) where we could store the default reference of that stage...

So yeah, what do you think? just touching base before I start to implementing it... don't think is gonna be specially complicated 

/cc @zendesk/samson

**Comment by grosser** [comment]
on second thought, default_reference is ok since some users might hardcode it to a certain sha/tag

**Comment by nogates** [comment]
yeah, I was thinking the same, that some people could use the tag `stable` or something like that... will use `default_reference`... hopefully, I might have some time to implement it during this weekend.
