### ISSUE TITLE
Audits issue or misconfiguration (NGINX + PUMA)

### ISSUE THREAD

**Issue by m8051** [zendesk/samson#2763]
Hi folks.

First of all I'd like to thank you for this awesome project, I've migrated our deployment process based on capistrano to Samson and it is working like a charm, hovewer today I realized the Audits stopped working and wanted to give you a shout just in case you lads have seen this before and can give me a hand.

### Samson Version
    Samson v2265

### Affected Resource(s)
	Audits

### Samson Configuration Files

	NGINX
```
upstream samson {
    server unix:///home/deploy/samson/tmp/sockets/pumactl.sock fail_timeout=0;
}

server {
    listen 80;
    server_name samson;

    root /home/deploy/samson/public;

    try_files $uri/index.html $uri;

    location / {
        proxy_pass http://samson;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_http_version 1.1;
    }

    error_page 500 502 503 504 /500.html;
    client_max_body_size 4G;
    keepalive_timeout 70s;
}

```
    PUMA

```
app_path = File.expand_path( File.join(File.dirname(__FILE__), '..', '..'))
# Change to match your CPU core count
workers 4

# Min and Max threads per worker
threads 2, 20

# Default to production
rails_env = ENV['RAILS_ENV'] || "production"
environment rails_env

# Set up socket location
bind "unix://#{app_path}/samson/tmp/sockets/pumactl.sock"

# Logging
stdout_redirect "#{app_path}/samson/log/puma.stdout.log", "#{app_path}/samson/log/puma.stderr.log", true

# Set master PID and state locations
pidfile "#{app_path}/samson/tmp/pids/puma.pid"
state_path "#{app_path}/samson/tmp/sockets/puma.state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_path}/samson/config/database.yml")[rails_env])
end
 ```
 ### Actual Behavior

When clicking to Manage => Audits, I’m getting the following error:

<img width="806" alt="screen shot 2018-05-28 at 21 44 48" src="https://user-images.githubusercontent.com/2571020/40629771-5a035e28-62c5-11e8-866a-abd1448e1f19.png">

```
Started GET "/audits" for x.x.x.x at 2018-05-28 20:45:17 +0000
Processing by AuditsController#index as HTML
  Rendering audits/index.html.erb within layouts/application
  Rendered audits/_table.html.erb (40.5ms)
  Rendered audits/index.html.erb within layouts/application (45.0ms)
Completed 500 Internal Server Error in 52ms (ActiveRecord: 4.8ms)

ActionView::Template::Error (undefined method `name' for #<Deploy:0x00007fc8a94e3300>):
    12:       <td><%= link_to audit.action, audit_path(audit) %></td>
    13:       <td>
    14:         <% if global %>
    15:           <%= (begin; audit.auditable;rescue NameError;end) ? link_to_resource(audit.auditable) : "#{audit.auditable_type} #{audit.auditable_id}" %>
    16:           by
    17:           <br/>
    18:         <% end %>

plugins/env/lib/samson_env/samson_plugin.rb:81:in `block (2 levels) in <top (required)>'
app/helpers/application_helper.rb:109:in `link_parts_for_resource'
app/helpers/application_helper.rb:114:in `link_to_resource'
app/views/audits/_table.html.erb:15:in `block in _app_views_audits__table_html_erb___2900724691460940953_70249998289360'
app/views/audits/_table.html.erb:10:in `_app_views_audits__table_html_erb___2900724691460940953_70249998289360'
app/views/audits/index.html.erb:14:in `_app_views_audits_index_html_erb__825720780632580505_70249998836160'
```

### Context

The Audits option used to work well as far as I remember when running the rails app through puma and listen to TCP:3000, not sure if using NGINX to proxy pass the requests to puma is when the issue began.

Thanks in advance for any help/support provided.

**Comment by grosser** [comment]
not nginx

error is coming from `      parent = " on #{env.parent.name}" if env.parent`
... which is a bug with the new "deploy env var" feature

https://github.com/zendesk/samson/pull/2666
/cc @nogates 

I'll whip up a fix, should be simple

**Comment by m8051** [comment]
Thank you for your prompt reply @grosser.

Could you please give a few tips on how to apply the patch/fix when available?

I also tried to bump from v2265 to v2280 by simply pulling the code and running bundle install but I reckon I missed some any other important step as the streaming did not work at all and I believe the process to upgrade to a new version requires more actions.

**Comment by grosser** [comment]
check out https://github.com/zendesk/samson/pull/2764 then `bundle exec rake db:migrate` and you should be good to go

for streaming please make a new issue

**Comment by m8051** [comment]
I will, thanks a mil @grosser

**Comment by m8051** [comment]
Checked [#2764](https://github.com/zendesk/samson/pull/2764/) out and Audits are back however [streamings are failing](https://github.com/zendesk/samson/issues/2766)

```
RAILS_USER=deploy RACK_ENV=production RAILS_ENV=production bundle exec rake db:migrate
== 20180528222146 DeleteDeployEnvVars: migrating ==============================
== 20180528222146 DeleteDeployEnvVars: migrated (0.0517s) =====================
```

Please feel free to close this out, thanks @grosser.
