### ISSUE TITLE
Allow not using CPU limits on k8s apps

### ISSUE THREAD

**Issue by rata** [zendesk/samson#2820]
Hi!

We've just hit an issue with latency sensitive applications on kubernetes. We wanted to make sure you were aware too, just in case it helps you. We are using an old version of samson, so not sure this really applies now. But as far as I can see, it applies (will look in detail next week).

The thing is just setting CPU limits for pods. When this is done, as the default CFS period is big (100ms) in case of k8s, this can cause quite some big delays (100ms :)) on containers just to cap the CPU. This affects a lot p99 or p95 response times (in our case, at least).

There is a bug that was opened in kubernetes here[1], that I think it wasn't quite clear what it implied for latency sensitive apps at first. The documentation (as that bug says) is misleading too. Is quite long, but interesting :) 

Here is a screenshot of some charts (the deploy was just before 13hs) after removing the CPU limits on one of our apps. The mean and p95 queue time was reduced a lot and the response time by half, too. 

![image](https://user-images.githubusercontent.com/70861/41795382-e54bb260-7638-11e8-9786-ebe3cae2ad28.png)

As reported in that bug, others have seen some incredible performance improvements in p99/p95 too[2]

Some comments I'd highlight about that long issue are these:
https://github.com/kubernetes/kubernetes/issues/51135#issuecomment-388617204
https://github.com/kubernetes/kubernetes/issues/51135#issuecomment-387139466

There are several ways to work on this. Changing the CFS period, disabling CFS quota entirely or not using CPU limits. At least that are the paths I understand from the issue so far, although is quite recent. The way to change the CFS period has been merged a few days ago, so not really an option on a released version yet. And there is a strong case that the doc is misleading and probably CPU limits don't need to be set on most cases.

The schedule CFS and quota are explained here:
https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt

And here a question that explain just that, just in case: https://unix.stackexchange.com/questions/213971/what-is-difference-between-different-cpu-cfs-period-us-values

We are using v1556, so the code is quite different. At that version only limits is set (no requests), and we just changed one line to use requests instead of limit. I see the code changed a lot, but as far as I tried you can't set the limit to 0 or something to disable (kubernetes won't accept the yaml).

So, unless I'm missing something in samson code, I guess this is not possible to change (i.e. not set cpu limit).

I think it's worth having a way to not set CPU limits on the yaml sent, given the consequences it can have for latency sensitive apps. What do you think?

Sorry if you were aware of this and I missed something! :)

Thanks a lot!

[1]: https://github.com/kubernetes/kubernetes/issues/51135 
[2]: https://github.com/kubernetes/kubernetes/issues/51135#issuecomment-373454012

**Comment by grosser** [comment]
options would be:
 - set limits to 0 and make samson understand that as "do not set"
 - add a checkbox to the deploy-group-role that says "No limits"
 - have a global ENV var to disable limits
 - have a per project setting to disable limits

which of them sounds best to you ?

**Comment by rata** [comment]
I think we are fine with any of them. Maybe the ones that are per-project are more flexible, but I think we would not need it at all.

Would any of them work for you too?

**Comment by grosser** [comment]
I think per deploy-group-role makes a lot of sense since it would cover cases where only for example an app server gets no limit and the rest gets them.

/cc @jonmoter
