### ISSUE TITLE
Autocompletion on Staging/Deploy page leaves box red / keeps error message

### ISSUE THREAD

**Issue by ElliotVilhelm** [zendesk/samson#2851]
Howdy,

I've noticed that when using the autocomplete in the staging deployment tab the error message of there not being a matching branch stays. If you type out the entire branch name, this goes away. 
### Autocompleted
<img width="679" alt="screen shot 2018-07-13 at 4 19 56 pm" src="https://user-images.githubusercontent.com/22024236/42717865-f6a3b50e-86b8-11e8-9982-1935844f9436.png">

### Typed Out
<img width="714" alt="screen shot 2018-07-13 at 4 22 30 pm" src="https://user-images.githubusercontent.com/22024236/42717893-1228c7b0-86b9-11e8-9447-e56646d01944.png">

**Comment by grosser** [comment]
hmm tried that but worked fine ... can you elaborate what you type ?

I tried
```
grosser/foo -> error
master -> ok
```

**Comment by ElliotVilhelm** [comment]
Hey, just tried it again and the issue is the same. When typing 'ep' it suggest the auto completion of `epourmand/PA-991` which I select. After selecting the text box fills with the auto completion but remains red like the first image above. If I choose to not use the autocompletion and I type out `epourmand/PA-991` the text box goes green.

**Comment by grosser** [comment]
https://zendesk.atlassian.net/browse/BRE-827
