### ISSUE TITLE
Github auth problem

### ISSUE THREAD

**Issue by m0n9oose** [zendesk/samson#2876]
I'd like to setup samson to deploy apps from github without automation, just a simple UI with "deploy" button.

I have running instance of Samson and github account for samson with access to repos. Trying to authenticate in guthub with valid credentials getting error on redirect: github redirects me to `localhost:3000` instead of samson's  host.

As far as i can see in code and setup.md there's some steps with setting up an github application and redirect urls, but i don't get this. Why do i have to set up anything else but samson itself? Samson knows it's host (`DEFAULT_URL`) already. What's the problem to authorize samson as oauth client without additional settings? I don't need any webhooks from github and other stuff.

**Comment by grosser** [comment]
the github app needs to point to the samson instance I think ... there might be ways around that somehow, but I afaik it's required

**Comment by m0n9oose** [comment]
the problem i don't even need a github application. I just need to setup samson to grant some permissions (read repos) and that's it. There's no need to provide any additional urls or anything else for this workflow

**Comment by grosser** [comment]
note sure if we are talking about the same thing ...
 - to use github auth you need a github app that has the redirect location set to samsons url
 - to allow samson to check commits/prs etc you need a github token
