### ISSUE TITLE
Use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [zendesk/samson#2891]
Would you be up for using [Dependabot](https://dependabot.com) to automatically keep the `Gemfile` and `Gemfile.lock` for Samson up-to-date?

I built it and can help with setup if you're keen. Running it on [my fork](https://github.com/greysteil/samson/pulls) the initial PRs all look pretty backwards compatible.

It's totally free for open source and always will be, but I do have an ulterior motive in asking you to use it on Samson: I'm keen to get more open source apps using it so I can use the data on the CI runs for dependency updates to find bugs in new releases and point the maintainers to the failing CI run as a reproduction step.

Having well-tested open-source apps like Samson use it should enable Dependabot to do awesome things, like automatically test release candidates of Rails and report back on any breakages, etc. For example, it could have helped find the Rails regression we just ran into in #2883. I've got some work to do on my side to make that a reality, but I'm confident I can get it done, and in the meantime I think it would save you some time keeping Samson up-to-date.

What do you reckon?

**Comment by grosser** [comment]
I'm not a big fan of these automatically update all dependencies approaches, afaik we are doing just fine with updating once a new rails release is out ... this bump-every-patch approach would add a lot of PRs/fixing-overhead/brittleness with very little benefit to us (maybe some benefit to gem providers as they get quicker feedback)

The automatically test against rails master and open issues for them sounds interesting.

**Comment by greysteil** [comment]
@grosser those are totally sensible objections, but can I convince you to give it a try?

You'd be doing me a favour, so I'd be more than happy to do the work to review, fix-up and test the initial pull requests to get Samson totally up-to-date. If you don't like it then you can just disable and have updated versions of a few dependencies.

**Comment by grosser** [comment]
This is not really a personal fun project that I'd be ok with messing around on.
Also there are multiple alternative services that do the same thing, so if we wanted this feature we should pick the one that fits best and not on first-come-first-serve basis.

Ultimately I'd leave it up to @ragurney / @dragonfax  to decide since their team own samson now

**Comment by ragurney** [comment]
I think I'm with @grosser on this one. We have yet to have this come up as an issue, and if we were to use such a tool I think it would merit more of an in-depth discovery/evaluation process. I'll close this for now, but revisit if @dragonfax has a different opinion.
