### ISSUE TITLE
Deploy console doesn't update in real time

### ISSUE THREAD

**Issue by klaus993** [zendesk/samson#2923]
Hi @grosser 

While testing out Samson v2385 I noticed that the deploy console does not show new lines as they come; it simply stays empty until the deploy finished, then I hit ctrl+R and all the output is there.

Looking at the logs, I can see this while deploying:

```
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 127.0.0.1 at 2018-09-05 17:48:26 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 127.0.0.1 at 2018-09-05 17:48:26 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/cable" for 201.216.209.173 at 2018-09-05 17:48:28 +0000
Started GET "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:28 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:28 +0000
Started GET "/ping" for 127.0.0.1 at 2018-09-05 17:48:38 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 100.96.110.1 at 2018-09-05 17:48:38 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 127.0.0.1 at 2018-09-05 17:48:38 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 100.96.110.1 at 2018-09-05 17:48:42 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 127.0.0.1 at 2018-09-05 17:48:42 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/ping" for 127.0.0.1 at 2018-09-05 17:48:42 +0000
Processing by PingController#show as HTML
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/cable" for 201.216.209.173 at 2018-09-05 17:48:43 +0000
Started GET "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:43 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:43 +0000
Started GET "/cable" for 201.216.209.173 at 2018-09-05 17:48:48 +0000
Started GET "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:48 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:48 +0000
Started GET "/cable" for 201.216.209.173 at 2018-09-05 17:48:55 +0000
Started GET "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:55 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for 201.216.209.173 at 2018-09-05 17:48:55 +0000
Started GET "/ping" for 100.96.110.1 at 2018-09-05 17:48:56 +0000
```

Maybe the WebSockets errors are related? But, even with that, is it not supposed to work even without using WebSockets?

Can you orient me a little here? We have samson deployed in kubernetes with the same setup we have with Samson v1556, which works OK (with an AWS ALB in front of it, which provides native HTTP/2 and WebSockets support). Is there something new about the console streaming that I'm not aware of and needs to be taken care of in order for that to work?

Thank you in advance.

**Comment by grosser** [comment]
check cmd+opt+i in chrome to see any websocket errors (they should appear after ~5s on every page)

**Comment by grosser** [comment]
`Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )` <- is most likely the reason :/

**Comment by grosser** [comment]
websockets handle the streaming of the deploy output (since streaming connections were limited at 6 ... so after opening 6 samson tabs every new samson page would refuse to load)

**Comment by grosser** [comment]
ggooggle for aws alb + websockets ... or check if there is any other proxy infront of it that might be breaking websockets

**Comment by grosser** [comment]
Need https://www.nginx.com/blog/websocket-nginx/ ... that's what I added to
our nginx :)

**Comment by klaus993** [comment]
Yes, thanks, that worked!

Sorry for bothering you, this had nothing to do with samson D:

**Comment by ibrahima** [comment]
Hi! Could either of you provide an example of your full NGINX config for Samson? I just upgraded to the current release of Samson and am experiencing the same issue. I get a 404 on the /cable route.

in nginx logs:

xx.xx.xx.xx - gradescope [29/Apr/2019:02:24:34 +0000] "GET /cable HTTP/1.1" 404 45 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"

In rails logs:

Started GET "/cable" for xx.xx.xx.xx at 2019-04-29 03:44:45 +0000
Started GET "/cable/"[non-WebSocket] for xx.xx.xx.xx at 2019-04-29 03:44:45 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: )
Finished "/cable/"[non-WebSocket] for xx.xx.xx.xx at 2019-04-29 03:44:45 +0000

I got most of my Nginx configuration from https://github.com/puma/puma/blob/master/docs/nginx.md but right now I commented out some of the less relevant stuff: https://gist.github.com/ibrahima/3f984de19e9e57d7e24dc50b5e64479e . I am not sure why this is happening. I have also recently switched over to running Puma via systemd, again using the Puma recommended systemd unit file. Not sure if that could be related.

Thanks!

**Comment by klaus993** [comment]
Hi @ibrahima 

What I did is add a file in `/etc/nginx/local-conf.d/` (and include it in the server configuration of the main nginx config file, in our case `/etc/nginx/local-conf.d/sites-enabled/default.conf`) with the following contents: https://gist.github.com/klaus993/a796545d1dec20b488d3349b0940a4d8

That worked right away.

**Comment by ibrahima** [comment]
Thanks! But I'm still having the same issue, possibly because my Samson instance is behind an ELB (for SSL mostly). It looks like there might be some fiddling needed to set up websockets behind an ELB, will have to investigate further.

**Comment by ibrahima** [comment]
Just wanted to give a little update that I switched over to an Application Load Balancer (ALB) which supports Websockets natively, and things just worked, and the updates are noticeably faster than they used to be. Nice!

Random question, I notice that samson is not set up to use redis for ActionCable, is that just because it's intended to run on a single process only anyway? Thanks!

**Comment by grosser** [comment]
Samson runs as a single process multithreaded server, lot of this is to avoid dependencies. Atm samson can run without any extra software installed (in-memory cache + sqlite). If it ever hits scaling limits we can look into options, but trying to keep things simple for simple usecases.

**Comment by ibrahima** [comment]
Makes sense, samson is probably a super low-traffic server, and I appreciate the simplicity!
