### ISSUE TITLE
support builds for multiple dockerfiles forces samson/dockerfile usage

### ISSUE THREAD

**Issue by rata** [zendesk/samson#2985]
Hi!

I'm trying to upgrade samson, but I think commit a236012267657236067b3372909fc7bbc3629a4e forces to use `samson/dockerfile` on the `containers[]`.

Before the upgrade, samson used to only update the image sha on the first container. This worked fine for me because the apps I use contain only one container that needs to be built and then several side-car containers (typically an nginx and a log collector).

When trying to use the new version (for https://github.com/zendesk/samson/pull/2970, thanks again @grosser !), a deploy fails. The issue is that samson updates the images in all containers (the nginx and log collector too). And this fails with address already in used, as all bind to localhost. But of course, the issue is that sidecars containers are not used (images are specified for them).

The way I found to prevent this is setting `samson/dockerfile: none` on the sidecars containers. But for me use case, it has several problems:

- In a way, it's not backwards compatible as yaml that were working are not working any more
- So, it needs to be done on all applications for sidecars containers (this is not trivial, though)
- The syntax is not valid in k8s, so if you try to use kubectl or need some kind of compatibility, you need to add a hack. As trying to deploy with kubectl, for example, says:

```
error: error validating "kubernetes/wido-web.yml": error validating data: [ValidationError(Deployment.spec.template.spec.containers[1]): unknown field "samson/dockerfile" in io.k8s.api.core.v1.Container, ValidationError(Deployment.spec.template.spec.containers[2]): unknown field "samson/dockerfile" in io.k8s.api.core.v1.Container]; if you choose to ignore these errors, turn validation off with --validate=false
```

I think that maintaining the syntax compatible with k8s is importante, as if not the kubernetes dashboard or some other tools complementing this can't be easily used without patches.

What do you think of using a `metadata.annotation` (that are intended to be used by software) to mark either multi dockerfile builds enabled or disabled (with some default) and maybe specify the dockerfile for each container there, when enabled?

Like `metadata.annotations.zendesk/samson.multi-dockerfiles-enabled: true` to mark this behavior. Or having to mark it disabled to return to previous behavior?

That would keep the yaml syntax valid for deployments that do not use multi docker files, at least.

But, if you want also, something like:

```
metadata.annotations.zendesk/samson.dockerfile[container-name]: Dockerfile.new
```

To keep the syntax valid and specify which containers use which docker files for samson builds.

The main issue for me is to change all projects (all use sidecars :-/) and have the hard requirement of doing it in a way that breaks the kubernetes syntax, so it won't be possible to interoperate with other tools easily.

What do you think?

**Comment by grosser** [comment]
syntax:
yeah we need to make it compatible .... but I also want to keep it in the
containers[] to make it less confusing
I'll see if there is a nice way of making it work in there and try to add
some kind of validation against kubectl so it does not happen again

dockerfiles:
easiest option is to add an env var that makes `none` the default again ...
then you can upgrade slowly and then turn it off after

**Comment by rata** [comment]
On Mon, Oct 08, 2018 at 08:33:18AM -0700, Michael Grosser wrote:
> syntax:
> yeah we need to make it compatible .... but I also want to keep it in the

Cool, glad to know you also want this :)

> containers[] to make it less confusing
> I'll see if there is a nice way of making it work in there and try to add
> some kind of validation against kubectl so it does not happen again

Hmm, I don't think there is one, except it is a comment...

> 
> dockerfiles:
> easiest option is to add an env var that makes `none` the default again ...
> then you can upgrade slowly and then turn it off after

Sorry, didn't follow. Env var where? Do you mean in samson .env?

**Comment by grosser** [comment]
yeah, the env var would make the non the default either in .env or set
somewhere else

**Comment by rata** [comment]
Thanks a lot! :)
