### ISSUE TITLE
Configuration knob to see output of prerequisite containers

### ISSUE THREAD

**Issue by rata** [zendesk/samson#3003]
Hi!

After https://github.com/zendesk/samson/pull/2996 I realize that seeing the output of the containers is useful for us.

The thing is: if we use the prerequisite jobs just to run a 1-off job (like a data migration or something), then if all goes well, there is no way to know which "deploy" run which script, what was it's output, etc. The only case were it is shown is if the 1-off job fails.

I tried to create a configuration knob (env var) to enable this, but I'm missing something that should be really simple to iterate the correct pods and get it's output. The code is pretty simple (just add a `show_logs_on_success` param to `deploy_and_watch`) and inspired the functions to get the logs from `show_failure_cause`.

Do you think it's okay to have a config know like that?

Another alternative I saw was something like this: https://github.com/zendesk/samson/pull/2665/ that references this: https://github.com/zendesk/samson/issues/2608

In any case, seeing the output for a 1-off job seems better to me (is more easy to know which script run, which things it processed, etc.). The other issue seems, honestly, like another route cause and different solutions seem better.

If this approach is fine (env var to always show logs after prerequisite runs), I'll continue to play with this tomorrow :)

Thanks!

**Comment by grosser** [comment]
I like the idea of showing logs for 1-off pods, super useful for migrations
:)
... metadata.annotations.samson/show_logs_on_success or so ... ideally it
would stream the logs while it is executing, but that might be tricky
