### ISSUE TITLE
Private repository

### ISSUE THREAD

**Issue by jyr** [zendesk/samson#3040]
Hi,

I trying to run samson with a private repo with the next config:

url: git@github.com:myorg/myrepo.git
branch: my-branch

and I get the error:

Repository Path 'git@github.com:myorg/myrepo.git' is unreachable

Samson works with private repositories?

Thanks

**Comment by grosser** [comment]
yes, the user samson runs as needs an ssh key that has access to that repo, try logging in as the user samson runs as and debug it that way

**Comment by jyr** [comment]
Hi, 

@grosser How can I change or where user samson?

**Comment by grosser** [comment]
ask whoever deployed your samson instance, it starts with a user ... that user needs the ssh key :)

**Comment by jyr** [comment]
I run samson on local environment, now ask about ssh passphrase:

```
CACHE Project Exists (0.0ms)  SELECT  1 AS one FROM `projects` WHERE `projects`.`permalink` = 'myproject' LIMIT 1
Enter passphrase for key '/Users/myuser/.ssh/id_rsa':
get https://api.github.com/repos/org/repo
```

I tried with ssh-add bla, Samson has some documentation about that?

Thanks

**Comment by grosser** [comment]
use a key without a passphrase
there are no docs on this, I'd hope there plenty of docs on how to setup
keyless sshkeys
