### ISSUE TITLE
Configuring stmp gmail

### ISSUE THREAD

**Issue by danihodovic** [zendesk/samson#3049]
Hi,

I'm unable to configure smtp to use Google's smtp server.

### Config
```
SMTP_URL: 'smtp://smtp.gmail.com:587'
SMTP_USER: 'testdeployer5534@gmail.com'
SMTP_PASSWORD: '<password>'
```

### Stacktrace
```
! Unable to load application: URI::InvalidComponentError: bad component(expected userinfo component or user component): testdeployer5534@gmail.com
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
URI::InvalidComponentError: bad component(expected userinfo component or user component): ambdeployer@gmail.com
  /usr/local/lib/ruby/2.5.0/uri/generic.rb:404:in `check_user'
  /usr/local/lib/ruby/2.5.0/uri/generic.rb:476:in `user='
```

Presumably this is because we assign the user to the smtp_url object and in this case the user contains an @ symbol which is considered invalid. If I remove the @ symbol the problem is resolved.

https://asciinema.org/a/SxQ69dVfLXMleXAboQVR09Vml

**Comment by grosser** [comment]
try without the `@gmail.com`

**Comment by danihodovic** [comment]
https://github.com/zendesk/samson/pull/3181

=)
