### ISSUE TITLE
API endpoint to see what is currently deployed

### ISSUE THREAD

**Issue by danihodovic** [zendesk/samson#3051]
I've been looking around in the issues and digging in code to see if I could find a JSON endpoint to retrieve the current deployed commit for a specific project and stage. Does such an endpoint exist?

**Comment by grosser** [comment]
you can search by deploy-group search[group]=DeployGroup-123
adding stage_id search should be easy to, would go into app/controllers/deploys_controller.rb:157 ... want to try to make a PR ?

**Comment by danihodovic** [comment]
> you can search by deploy-group search[group]=DeployGroup-123

Could you give an example with the full path?

> adding stage_id search should be easy to, would go into app/controllers/deploys_controller.rb:157 ... want to try to make a PR ?

We map stages to deploy groups so if we can find the deployed commit in the deploy group that should solve the problem.

**Comment by grosser** [comment]
`/projects/kube_node_monitor/deploys.json?search%5Bstatus%5D=&search%5Bgroup%5D=DeployGroup-123`
