### ISSUE TITLE
How does the preventing with preStop hook works?

### ISSUE THREAD

**Issue by rata** [zendesk/samson#3080]
Hi!

I don't follow how adding a 'sleep 3' as pre-stop hook makes a deploy not lose requests. Can you please explain what am I missing?

IIUC, If all the containers in a pod have this (as it may happen), then they will all die ~3 seconds later. Why doing it would change anything regarding the coming requests? 

I can see it happens if the pod is removed from the service and this sleep is enough to finish the inflight requests. But this is very fragile, and there is an inherent race condition there, as it is quite possible to not finish the inflight requests in that time.

We are using nginx and as a prestop we do an `nginx -s quit`. That will finish nginx when the inflight requests have been processed, I think.

Am I missing something? How is this supposed to work?

Also, I'm not sure we want to inject this in all pods. Would it be okay to add an env var to disable this behavior by default? (instead of changing all our yamls to use the annotation)

**Comment by grosser** [comment]
you should totally use `nginx -s quit`

the 3s is for the time our routing layer takes to react to service changes since we don't send to the kubernetes service but to consul which knows about all the endpoints directly, but has a slight lag

(feel free to reopen if that's still unclear/confusing)

**Comment by rata** [comment]
Not sure I followed in detail, but I understand it's something quite specific to your setup and we will continue to use `nginx -s quit`. That is enough, I think :)

Thanks!
