### ISSUE TITLE
Trigger deploy on new Build

### ISSUE THREAD

**Issue by dasch** [zendesk/samson#3110]
It's possible to trigger a deploy whenever a new Release is created, but it's not possible to trigger a deploy when there's a new Build.

The reason for wanting this is that a Build may have side effects (e.g. uploading artifacts to a registry) and some pipelines need to wait for the Build to complete. A Release is created immediately on merges, so a deploy that depends on those artifacts will fail.

**Comment by grosser** [comment]
deploys can wait for builds (docker image building) via some settings, so that might work
if you are looking for asset builds then how about using a webhook at the end of the asset build to tell samson to create a release and deploy ?
