### ISSUE TITLE
Documentation for external building is internal for Zendesk

### ISSUE THREAD

**Issue by nayena** [zendesk/samson#3128]
The link for the guide to set up external builds is pointing to an internal zendesk document.

![the link](https://user-images.githubusercontent.com/584251/51313624-4d68dd00-1a4e-11e9-8e7f-bc57750c8c3c.png)

The link in question can be found at [/app/views/projects/_docker_fields.html.erb#L10](https://github.com/zendesk/samson/blob/master/app/views/projects/_docker_fields.html.erb#L10)

Is there any possibility to extract something for the open source community to read?

**Comment by grosser** [comment]
@sathishavm from https://github.com/zendesk/samson/pull/2714 
can you add all docs in samson or make the link optional via an env var ?
also "click [here] to know more" -> "[details]"

**Comment by grosser** [comment]
@nayena plz keep raising issues like this, we are often blind to subtle thing like that :D

**Comment by nayena** [comment]
@grosser You bet'cha! I remember samson fondly from my own zendesk days, years ago. I'm very happy to be using it again!
