### ISSUE TITLE
Difference between deploy groups and environments?

### ISSUE THREAD

**Issue by danihodovic** [zendesk/samson#3171]
I'm not sure if this is documented somewhere. What is the difference between these two entities exactly? There seems to be an overlap at least conceptually. I consider both of them to serve the purpose of what I usually call environments, e.g staging, QA, production.

So why do both deploy groups and environments exist? Why can't the functionality be combined into one entity?

**Comment by grosser** [comment]
deploy-groups can be used to have different regions per environment
we have 20+ deploy groups in our "production" environment for example
it's possible to just have 1 environment and then deploy-groups for "staging/production" 🤷‍♂️
