### ISSUE TITLE
Registering build fails when cloning takes more then 5 seconds

### ISSUE THREAD

**Issue by thrawny** [zendesk/samson#3217]
Relates to #3198 but did not know exactly what the problem was when I created that issue.

How to reproduce;
Find a "big" repo, one that takes 10 or so seconds to clone. Then register a build when the repo is not in the cache. The request will hang for about 6 seconds (on my machine) then return with a 422 "not a valid git reference".

I don't know how to solve this problem in a good way, but I think a 5 second timeout is a bit small in this case. Something like 20-30 seconds timeout would be better and then fail with a better error message than the very confusing "not a valid git reference".

**Comment by grosser** [comment]
the issue is that it uses the default timeout for the TerminalExecutor which is 5s
https://github.com/zendesk/samson/pull/3228 might work ... I'll try another approach next

**Comment by grosser** [comment]
https://github.com/zendesk/samson/pull/3237 should do the trick ...

**Comment by thrawny** [comment]
Amazing, thx!
