### ISSUE TITLE
Using slack-app /deploy fails, with regex match returning nils

### ISSUE THREAD

**Issue by nayena** [zendesk/samson#3218]
When running `/deploy project ref stage` on slack, the following is returned:

```
Sorry, </projects/hello-kube|Hello Kube> doesn't have a stage named ``
```

Looking at [/plugins/slack_app/app/controllers/slack_app_controller.rb#56](https://github.com/zendesk/samson/blob/master/plugins/slack_app/app/controllers/slack_app_controller.rb#L56), it uses a combination of `match` and `captures`, which in ruby 2.5.3 doesn't return the expected results:

```
irb> foo = "one two three"
=> "one two three"
irb> project_name, ref_name, stage_name = foo.match(/([^\s\/]+)(?:\/(\S+))?\s*(?:to\s+(.*))?/).captures
=> ["one", nil, nil]
```

However, using a combination of `scan`, `flatten` and `compact` it will yield the expected result, as seen below:
```
irb> foo = "one two three"
=> "one two three"
irb> project_name, ref_name, stage_name = foo.scan(/([^\s\/]+)(?:\/(\S+))?\s*(?:to\s+(.*))?/).flatten.compact
=> ["one", "two", "three"]
```

**Comment by nayena** [comment]
However, running the regexp through rubular.com, it yields:
```
Match 1
--
1. | one
2. |  
3. |  

1. | two
2. |  
3. |  

1. | three
2. |  
3. |  
```

**Comment by grosser** [comment]
fixed by https://github.com/zendesk/samson/pull/3247
