### ISSUE TITLE
Samson only pushes latest tag to dockerhub, not individual release tag

### ISSUE THREAD

**Issue by nayena** [zendesk/samson#3263]
About a week ago, it looks like samson isn't being pushed to dockerhub as a versioned tag and only under "latest" tag.

See https://hub.docker.com/r/zendesk/samson/tags

It stopped after v2668 and the latest tag here on github is v2683, so 15 releases are missing so far. I'd love to upgrade, but am somewhat reluctant to using the latest tag, as I like to version lock things.

**Comment by grosser** [comment]
yeah I noticed, still on my todo list ... tried a few different things already but nothing is working :(
... it's set to build any tag atm and tags are getting pushed to dockerhub 🤷‍♂️

**Comment by nayena** [comment]
It looks like whatever you did - or didn't do, fixed it. It is currently pushing images again :tada:
