### ISSUE TITLE
Do we have a way to know who is deploying?

### ISSUE THREAD

**Issue by kureikain** [zendesk/samson#337]
I want to do some custom notification when deploying(to hipchat, custom email template, custom deploy message...). I don't know how to do that so I'm thinking I will do notifcation on repository itself. Such as in Capistrano, before deploying I can send custom notification. The problem is:

- How can I know who is deploying? Do we have an end-point API on Samson that I can curl it to get response
- Does we have any env variable about current deployment is set/pass into command

**Comment by jwswj** [comment]
Samson has deploy hooks, so you could build a custom plugin (similar to the slack and flowdock ones - https://github.com/zendesk/samson/tree/master/plugins/slack). These plugins know what is being deployed and by which user.

Ideally you'd build:
- A generic Hipchat plugin (by copying the slack/flowdock plugins)
- Change your fork of Samson to have a custom email template and deploy message (or do this with Capistrano)

> How can I know who is deploying? Do we have an end-point API on Samson that I can curl it to get response?
It's really the wrong way to think about it. You should use notifications, but you could hit https://github.com/zendesk/samson/blob/master/app/controllers/deploys_controller.rb#L16-L24 to get a list of all projects which are currently being deployed. Then get the deploy and make a few more calls get the user.

> Do we have any env variable about current deployment is set/pass into command?
You can set environment variables when setting up a stage. They can then be used in your capistrano scripts.

**Comment by zendesk-shender** [comment]
Also to answer the last point:

> Do we have any env variable in current deployment to set/pass into command?

Yes, when a deploy is executing, there are ENV variables containing the deployer details (https://github.com/zendesk/samson/blob/master/app/models/job_execution.rb#L104)
So in your capistrano task you can access the ENV['DEPLOYER'], etc...
