### ISSUE TITLE
Run samson forever

### ISSUE THREAD

**Issue by italolelis** [zendesk/samson#340]
Hi everyone,

I'm using samson and I like it very much. 
I have a question though, when I run *rails s* in terminal, if I hit ctrl + C the server shuts down, it's ok for a development mode, but how can I run this forever? Without worring with ctrl + C?

Thank you very much!

**Comment by steved** [comment]
When running with puma, you can send a `USR1` to signal to the samson process and it will ensure all running jobs are finished and then pass a `USR2` signal to puma for a seamless reload.

**Comment by italolelis** [comment]
Thanks @steved I'll check that. :+1:

**Comment by italolelis** [comment]
Hey @steved 
Thanks man, I've read some articles that helped me configure puma and forman with nginx. Now it's all working.
