### ISSUE TITLE
Handle webhooks in different orders

### ISSUE THREAD

**Issue by mariovisic** [zendesk/samson#359]
Currently when CI sends a webhook for a successful build on the release branch it creates a release for the passed in commit. In some circumstances it's possible for hooks to come in in reverse order. So for example I have two builds running very close together, build A and B. If build B finishes first for some reason, it's possible that A failed and was restarted, we'll get a webhook for B and then a webhook for A.

When this happens we get a release that displays no commits are present or pull requests, because the changeset will be B..A where A is an older commit than B.

I think in these circumstances one option would be to not create a release, when we know the commit on the webhook already features in the latest release.

Thoughts?

**Comment by mariovisic** [comment]
Let me know if my proposed solution of not creating a release when the commit is downstream of the latest releases commit is OK, if so; i'll send a patch with tested code.

**Comment by mariovisic** [comment]
Any news on this @jwswj ? Should I send a patch to not create a release? Is that the desired behaviour in this case?

**Comment by sandlerr** [comment]
:+1: on this, definitely sensible not to create a release when its commit is already released. Would be great if you can send a patch!

**Comment by jwswj** [comment]
Agree it shouldn't create a release if the commit is downstream of the latest release.

**Comment by mariovisic** [comment]
See #380
