### ISSUE TITLE
JavaScript compilation issues

### ISSUE THREAD

**Issue by mariovisic** [zendesk/samson#362]
Getting this JavaScript error when compiling assets:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module samson due to:
Error: [$injector:unpr] Unknown provider: t
```

Seems to be due to the recent JavaScript changes, works fine running locally and not compiled.

**Comment by sandlerr** [comment]
This works for me on master. What command did you run?

**Comment by mariovisic** [comment]
`rake assets:precompile`

**Comment by mariovisic** [comment]
Sorry, this happens once assets are precompiled, eg run `RAILS_ENV=production rake assets:precompile` then run the web server and it'll show that error in the JS

**Comment by mariovisic** [comment]
Maybe try this: `rm -rf public/assets tmp/* && RAILS_ENV=production rake assets:precompile && RAILS_ENV=production rails server`

I can reproduce it currently on master. On 7a6ecde4b5790e516744eb56b2c30a3a1675c96d the issue is not present, so the issue would be somewhere here: https://github.com/zendesk/samson/compare/7a6ecde4b5790e516744eb56b2c30a3a1675c96d...master

**Comment by mariovisic** [comment]
Have narrowed it down, the problem commit seems to be: 0ddbad3161a446167a8a55c3b17a468f0756c023

**Comment by zendesk-shender** [comment]
Hmm... wonder if the ng-annotate gem is being circumvented with the assets changes,  it looks like the angularjs injector service is trying to inject 't' which probably indicates a minified dependency name.

**Comment by zendesk-shender** [comment]
https://github.com/zendesk/samson/pull/364 should fix this.

**Comment by zendesk-shender** [comment]
This looks resolved now! Enjoy! :)

**Comment by mariovisic** [comment]
Awesome, works a treat, thanks @zendesk-shender :)
