### ISSUE TITLE
Feature request: pick up a kubernetes Role to deploy only if Resources are first defined for that stage

### ISSUE THREAD

**Issue by g-marius** [zendesk/samson#3630]
I ran into this setup issue today as I only wanted a certain configuration to be bound to staging only or even to just a pod. Here are the steps that got me into the issue:
 - created a new kubernetes role yaml and in samson
 - defined Resources to be allocated for pod998 only
 - attempted to deploy to staging, pod999 failed as it tried to pick up the config from the repo even though no Resources were allocated
`JobExecution failed: Role app-server-hpa for Pod999 is not configured, but in repo at 2a7a2029ef17f34826706ed0ba3282b6140bd310. Remove it from the repo or configure it via the stage page.` https://samson.zende.sk/projects/sms/deploys/853626

So was thinking that maybe there is a way to tell samson don't look at these k8s objects (deployment/pod/rc/hpa) in pods were Resources are not defined.

As a workaround I tried configuring the Resources for pod999, deploying my resource (hpa) with a replicaset of 0 but looks like kubernetes will still deploy this, maybe replicaset does not apply to all things. Not sure if I missed something here that would block attempting to deploy this resource.

Feel free to shut this feature request down if it does not make sense, or if it would complicate things even more.

**Comment by grosser** [comment]
stages can ignore roles ... see stage settings
