### ISSUE TITLE
PSA: be very careful with the `PRECOMPILE` variable around puma

### ISSUE THREAD

**Issue by stephgosling** [zendesk/samson#3726]
This is somewhere between a warning and a bug (nearer the warning end of that spectrum) and I hope it saves someone some time in the future.

Installation: v3109 via a custom `docker-compose.yml` based upon the development [`script/docker_dev_server`](../tree/master/script/docker_dev_server)

The [documentation](https://github.com/zendesk/samson/blob/master/docs/setup.md#production-assets) states that assets need to be generated _before running in production_ with a helpful rake command illustrating how to do so. One of the envvars passed to that rake command is `PRECOMPILE`. 

If `PRECOMPILE=1` happens to be set in the environment that `puma` starts in; for reasons I don't really understand, on launch Samson will immediately be in the 'restart state': that is to say all deploys will stall (i.e. pending) as Samson believes it is scheduled to restart: This is the case even for a brand-new installation with an empty database.

To reproduce, clone [my fork](https://github.com/stephgosling/samson), (specifically this [commit](https://github.com/stephgosling/samson/commit/f7e03b5a511972cb2fd7f72790a695561d6b4fd7) and simply `docker-compose up` and then login to localhost:3000. You'll see the following (should say _deploying_, not _restarting_)

![Screenshot_20200219_234646](https://user-images.githubusercontent.com/1391834/74887617-4e67ee80-5373-11ea-8025-14b034580606.png)

I came across this as I was reworking the startup script and trying to consolidate variables. It took me about 10 hours to get to the bottom of it and isn't confined to docker, setting `PRECOMPILE=1` in a 'real' environment behaves exactly the same way. I hope this saves someone some time in the future.

**Comment by grosser** [comment]
can you make a PR to crash the server when it starts in PRECOMPILE mode ?

**Comment by stephgosling** [comment]
hey @grosser
That's the issue, the server doesn't crash, and in terms of logging/console output it doesn't print anything odd at all. I had a look at all of the places that `PRECOMPILE` is looked for in the code and didn't see anything particularly amiss, and looking around  the `JobQueue` class I also don't particularly understand how `JobQueue.enabled` is set to true and when.
