### ISSUE TITLE
No rolling updates when project has a job role

### ISSUE THREAD

**Issue by thrawny** [zendesk/samson#3732]
The setup is I have a project with 2 roles.
A migrate role (job) that has `samson/prerequisite: "true"`and a server role (deployment) that runs a web service. Whenever I deploy this project, samson begins by removing everything and then proceeds by deploying the prereq job followed by the deployment. Is this the intended behaviour? I would except that the deployment would be deployed according to its rollingUpdate strategy. The result is that there is something like 30 second downtime whenever a deploy is made. I tried removing the `samson/prerequisite` but this does not change anything, samson still starts by removing everything.

I made a recording to clarify what I mean:
https://asciinema.org/a/304220
Here you see that the first thing that happens is that everything gets removed.

Maybe there is some configuration option that solves this, but I haven't found anything by reading the docs or source code. If this is the intended behaviour then I think the docs should be updated to reflect this.

**Comment by grosser** [comment]
that's too fast to be sure ... can you change migrate to do `sleep 60` to make sure ?

**Comment by thrawny** [comment]
Here is one with 60 second migrate: https://asciinema.org/a/XMFmq6jxnOs5VaJsfmDzuxX9g
We can see that the deployment gets replaced immediately when migrate starts, which causes downtime. Then when migrate is done, the deployment is changed again, but this time it seems like it is a rolling update.

**Comment by grosser** [comment]
does the migration deploy show before the Deployment in samson logs ? ... it should be apart by a minute.Maybe the setting is not working ... it's under metadata.annotations right ?
... the migration should be a Pod and not a Job, so it can stop when it fails

you should be able to see:
```
First deploying prerequisite ...
... job
Now deploying other roles ...
```

**Comment by thrawny** [comment]
So I changed the migrate role to a pod and then everything works as I would expect. I.e. the rolling update works properly.

However the documentation says prereq can be set on `Job/Deployment/Pod` so I still think there is something broken with jobs in particular. Having a job role should not break rolling updates for your other roles. 

In any case, thanx alot for the assistance!

**Comment by grosser** [comment]
awesome, yeah sounds like a bug with jobs!
