### ISSUE TITLE
<com.getbase.floatingactionbutton.FloatingActionsMenu

### ISSUE THREAD

**Issue by jano1991** [zendesk/samson#3794]
<com.getbase.floatingactionbutton.FloatingActionsMenu
                android:id="@+id/mainFab"
                android:layout_width="90dp"
                android:layout_height="90dp"
                android:layout_alignParentRight="true"
                android:layout_alignParentBottom="true"
                android:layout_margin="16dp"
                app:fab_addButtonColorNormal="@color/colorAccent"
                app:fab_addButtonPlusIconColor="#000"
                app:fab_labelStyle="@style/custom_fab">

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/picNote"
                    android:layout_width="65dp"
                    android:layout_height="65dp"
                    app:fab_icon="@drawable/text_reader"
                    app:fab_size="mini"
                    app:fab_title="  Picture note" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/ocrNote"
                    android:layout_width="65dp"
                    android:layout_height="65dp"
                    app:fab_icon="@drawable/ic_text"
                    app:fab_size="mini"
                    app:fab_title="Scan Text" />

                <com.getbase.floatingactionbutton.FloatingActionButton
                    android:id="@+id/textNote"
                    android:layout_width="65dp"
                    android:layout_height="65dp"
                    app:fab_icon="@drawable/ic_camera"
                    app:fab_size="mini"
                    app:fab_title="Text note" />
            </com.getbase.floatingactionbutton.FloatingActionsMenu>

_Originally posted by @Shahnwazh170 in https://github.com/zendesk/android-floating-action-button/issues/379#issuecomment-531941445_

**Comment by grosser** [comment]
wrong repo ? 🤷
