### ISSUE TITLE
Request: documentation for secrets usage

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#3807]
It's not really clear how the secrets work / can be used. The documentation mentions apis, resolving, etc. but doesn't really describe the basic usecase: "I want to use the secret in a build; how do I do it?".
It would be awesome to include it in https://github.com/zendesk/samson/blob/master/docs/secrets.md

**Comment by grosser** [comment]
does https://github.com/zendesk/samson/pull/3808 help ?
... if you want to use it in a docker build, you'd have to use it in a command.
... be careful not to set secrets inside the docker image though :)

**Comment by viraptor** [comment]
I guess what I was missing is literally:
> `secret://name` in the command text will be replaced with the secret value on execution.
