### ISSUE TITLE
Live demo leaking user info

### ISSUE THREAD

**Issue by Confuzed** [zendesk/samson#3858]
Your live demo is leaking github account names, actual names, and email addresses of the people that use it. The information is exposed on the Audit page. This information must be redacted or removed.

**Comment by Confuzed** [comment]
@grosser Thank you for addressing this with a PR so promptly. Unfortunately I see that the demo environment continues to show the user information on the audit page, so this is not resolved.

**Comment by grosser** [comment]
thx, fixed it by setting HIDE_USER_AUDITS :)
