### ISSUE TITLE
Can't remove a global lock in v3222

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#3863]
When trying to remove a global lock in v3222, I get an exception:

```
ActionController::MissingExactTemplate: LocksController#index is missing a template for request formats: text/html
```

**Comment by grosser** [comment]
tried it on latest and it works fine ... can you reproduce it ? ... what steps do you do to reproduce it ?
<img width="240" alt="Screen Shot 2020-09-29 at 9 14 42 AM" src="https://user-images.githubusercontent.com/11367/94584970-37a44700-0234-11eb-89f9-8ac4c50b5ac2.png">

**Comment by viraptor** [comment]
We ran into this when upgrading from a previous version... but there's some db migration mess happening as well, so I'll close this until we confirm that's not the case.
