### ISSUE TITLE
Trying to deploy while global lock is on causes exceptions

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#3864]
When trying to deploy while the global lock is on, I get an exception: (in v3222)

```
PG::NotNullViolation:

ERROR:  null value in column "job_id" violates not-null constraint
DETAIL:  Failing row contains (44710, 5, null, v370, 2020-09-29 06:27:39.747704, 2020-09-29 06:27:39.747704, null, null, null, t, 4, t, f).
```
at
```
...
File /home/ubuntu/samson/app/models/stage.rb line 95 in create_deploy
File /home/ubuntu/samson/app/models/deploy_service.rb line 16 in deploy
File /home/ubuntu/samson/app/controllers/deploys_controller.rb line 57 in create 
```

**Comment by grosser** [comment]
oh man ... this is soo old :D
https://github.com/zendesk/samson/pull/215 added it ...

so basically this is a feature to block 1-off jobs when things are globally locked I think
but it makes sense that whoever did the locking should be able to still deploy

**Comment by grosser** [comment]
fixed by https://github.com/zendesk/samson/pull/3865

**Comment by viraptor** [comment]
Awesome work. Thank you!
