### ISSUE TITLE
Warn/Lock messages are incorrectly normalized

### ISSUE THREAD

**Issue by shadowhand** [zendesk/samson#388]
It looks like samson does a lowercase transform on all messages, which makes messages like this end up weird:

> Wait until iOS testing is complete

Ends up as:

> Wait until ios testing is complete

Or another example:

> Check with Tim before this goes out, QA wanted to do another check

Ends up as:

> Check with tim before this goes out, qa wanted to do another check

This normalization makes the output worse, not better.

**Comment by grosser** [comment]
fixed by #389 

![screen shot 2015-05-06 at 10 42 43 am](https://cloud.githubusercontent.com/assets/11367/7499463/acdf9752-f3dc-11e4-87cf-759bd4a93c77.png)
