### ISSUE TITLE
Plugin system issue - Mysql2::Error: Table 'pusher.slack_channels' doesn't exist

### ISSUE THREAD

**Issue by gabetax** [zendesk/samson#393]
Seen on deploys#create:

```
Mysql2::Error: Table 'pusher.slack_channels' doesn't exist
plugins/slack/lib/samson_slack/samson_plugin.rb:19 in send_slack_notifications?
/data/samson/current/plugins/slack/lib/samson_slack/samson_plugin.rb:64 in block in <top (required)>
lib/samson/hooks.rb:61 in call
lib/samson/hooks.rb:61 in block in fire
lib/samson/hooks.rb:61 in map
lib/samson/hooks.rb:61 in fire
app/models/deploy_service.rb:56 in send_before_notifications
app/models/deploy_service.rb:19 in confirm_deploy!
app/models/deploy_service.rb:12 in deploy!
app/controllers/deploys_controller.rb:41 in create
```

/cc @grosser plugin system issue?

**Comment by grosser** [comment]
sounds more like missing migration to me ... either just rake db:migrate or the migrations are not run with the same env that samson is run with -> plugins are not active -> no migrations

**Comment by grosser** [comment]
is that staging or production ?

**Comment by gabetax** [comment]
production. @babbottscott just ran `rake db:migrate` that fixed it, but I'm unsure how the migration was skipped originally.

**Comment by grosser** [comment]
could have been because PLUGINS=all was not set and so the migration was not picked up ... we should make sure the next migration runs smoothly ...
