### ISSUE TITLE
assets:precompile not generate env plugin assets

### ISSUE THREAD

**Issue by Willis0826** [zendesk/samson#3948]
# Issue
I ran `RAILS_ENV=production PRECOMPILE=1 PLUGINS=all bundle exec rake assets:precompile --trace` with `v3290` can not generate `env` plugin assets under `public/assets` folder. Also, there are no error while running the command.

However, I can verify the `v3260` work as expected.

# Expected
I should be able to see `env` plugin assets after ran the precompile command.

# How to reproduce
1. `git checkout v3290`
2. `bundle`
3. `RAILS_ENV=production PRECOMPILE=1 PLUGINS=all bundle exec rake assets:precompile --trace`
4. `ls public/assets`
5. There is no `env` plugin

**Comment by grosser** [comment]
yeah, the add_assets_to_precompile hook is still getting called, but the fils are not rendered :/

**Comment by grosser** [comment]
found it ... it's an ordering problem :/

**Comment by grosser** [comment]
https://github.com/zendesk/samson/pull/3949

**Comment by Willis0826** [comment]
Thanks for the quick response and fix : )
