### ISSUE TITLE
Better approach to managing integrations

### ISSUE THREAD

**Issue by jwswj** [zendesk/samson#4]
The number of integrations with Samson could grow quite quickly, however not everyone wants them all to be visible when configuring stages.

It would be nice if super admins could have a place where they could toggle the integrations they would like for their version of Samson. This probably belongs as a new page in the admin drop down "Configuration"...

Thoughts @dasch @steved555 @tonymilne?

**Comment by sandlerr** [comment]
https://github.com/zendesk/samson/pull/259
