### ISSUE TITLE
Latest releases not published to Docker Hub

### ISSUE THREAD

**Issue by jamesmbourne** [zendesk/samson#4029]
It seems that the most recent version available on Docker Hub is [`v3346`](https://hub.docker.com/layers/zendesk/samson/v3346/images/sha256-1e1ae2cdf364dd7f665cc8632045d02bd0801adec9d17c6324a9a7cec3c00522?context=explore) but the most recent GitHub release is [`v3362`](https://github.com/zendesk/samson/releases/tag/v3362)

I cannot see any builds more recent than `v3346` which ran 5 months ago on https://hub.docker.com/r/zendesk/samson/builds/?page=1

Thanks!

**Comment by jamesmbourne** [comment]
Thanks @grosser - appreciate your efforts in continuing to maintain this. I will take a look at building from source and see if I can get the changes back into the upstream repo.

**Comment by grosser** [comment]
this was easy ... https://github.com/zendesk/samson/pull/4031
problem was that docker builds were [failing](https://hub.docker.com/repository/registry-1.docker.io/zendesk/samson/builds/7cccad22-bcb8-4be1-91e0-4d062944dfae)
... I had feared it's another auth or build setup issue :)
