### ISSUE TITLE
Possible Alternative to Samson?

### ISSUE THREAD

**Issue by yra-wtag** [zendesk/samson#4038]
Hi everyone,

As i saw in the readme that Samson is currently under maintenance mode. So was wondering if you guys have any tools that is similar in functionality. There is a list here https://github.com/ligurio/awesome-ci but it does not have something very close to it.

Specially the per project deployment interface Samson provides where you can encapsulate all the pipelines under a git project is something i have not seen in other projects. This really makes life easier if you need to manage a lot of different projects with different needs.

Drone looks interesting although not same https://github.com/harness/drone

If you have any suggestions please put them here.

**Comment by grosser** [comment]
we are migrating to spinnaker ... it's not the same though 😞

**Comment by yra-wtag** [comment]
Hi @grosser , Yeah spinnaker was the tool we also considered before moving to Samson. yeah not the same. Samson has some really cool features that i have not found in any tools.

**Comment by akshay-soni** [comment]
We have made a lot improvements to Spinnaker lately. Can you please connect me on Slack if there is anything specific? I will close this issue for now

**Comment by danihodovic** [comment]
I really liked Samson. Did Zendesk publish any document motivating the move from Samson to Spinnaker?

The ease of setting up Samson (single container), the easy of configuring application deployments and the number of integrations made Samson a pleasure to use. The UI allowed me to easily find out what was deployed where and to see the deployment history.

Just looking at the architecture of Spinnaker makes me think it's not even close in terms of simplicity: https://spinnaker.io/docs/reference/architecture/microservices-overview/

**Comment by grosser** [comment]
yeah, spinnaker is a complicated beast in comparison, would not recommend for a small setup :(
... also we are looking into moving to argocd next since spinnaker seems to not scale as we add more and more pipelines/clusters
