### ISSUE TITLE
User not able to login again to Samson using Github Id

### ISSUE THREAD

**Issue by tanpsingh** [zendesk/samson#4067]
There is an issue with the user log in. Samson and GitHub are not able to authorize the login to access the samson tool. Getting below error:

`[id:9ce0e0e0-a344-4d76-bd3f-9140025aacb9] [ip:49.37.162.3] Halted as unauthorized! threw :warden (called from /app/controllers/concerns/current_user.rb:26:in login_user) `

The user got deleted from Samson's user management and after he is not able to log in. Even though we have tried to revoke access from GitHub and then log in again but it's not working and getting the above error.

We are using samson login is integrated with Github therefore we using Github ID to access the samson tool.

**Comment by grosser** [comment]
users [have soft deletion](https://github.com/zendesk/samson/blob/master/app/models/user.rb#L12) so I think if you find the user and undelete them, things will work out

`User.with_deleted { User.find_by_email("foo").update_column :deleted_at, nil }`

**Comment by tanpsingh** [comment]
@grosser Thanks for your reply.

Do you know how we can undelete them? or can we do a hard delete and ask the user to log in with a GitHub id?

**Comment by grosser** [comment]
use the command I posted in the `rails console`

**Comment by tanpsingh** [comment]
Ok. Sure

I will try the above command.
Thanks alot.
