### ISSUE TITLE
Show latest tags when creating a new deploy

### ISSUE THREAD

**Issue by ncalca** [zendesk/samson#409]
A common use case when creating a new deploy is to deploy one of the tags that was recently created.

It would be nice to show the latest n (= 5 ?) tags in the following form so that the user can just click on one of them to create a new deploy.

![screen shot 2015-05-13 at 11 20 16](https://cloud.githubusercontent.com/assets/2805296/7607510/36e048f4-f962-11e4-8601-1f041f1d1ea9.png)

**Comment by mblaschke** [comment]
Or just set the default tag/branch as option in deployment stage settings

:+1:
