### ISSUE TITLE
Invoke hook when executing job?

### ISSUE THREAD

**Issue by kureikain** [zendesk/samson#415]
Hi,

Could we include hook for job executing. Just like deploy we have :before_deploy and :after_deploy, we should have something like :before_job and :after_job?

cc @zendesk

**Comment by jwswj** [comment]
What's the use case here for these type of hooks?

**Comment by kureikain** [comment]
I need it for extra notification when a jobs done, and I can notifiy on Hipchat/Slack so the whole of team aware of job execution and its result.

**Comment by jwswj** [comment]
Makes sense. Have a look through https://github.com/zendesk/samson/blob/0863afa0e89636ab3e36d20dd00ee97197407656/lib/samson/hooks.rb#L3-L14
&
https://github.com/zendesk/samson/blob/0863afa0e89636ab3e36d20dd00ee97197407656/app/models/job_execution.rb#L98
and put up a PR.
