### ISSUE TITLE
Install plugin as a Gem

### ISSUE THREAD

**Issue by kureikain** [zendesk/samson#417]
Is there a way we can distribute plugin as Gem and include them in Gemfile? 

cc @grosser @steved

**Comment by grosser** [comment]
Just make it  a gem and include it in the Gemfile or did you try that and it did not work ?

**Comment by kureikain** [comment]
My bad, I tried it but forgot to set `files` in Gemspec and it didn't include file so Gem.find_files in lib/samson/hooks.rb fail to find it for including. Thanks.

**Comment by grosser** [comment]
Sweet :D
What did you write ?
Can we link it in the readme ?

On Fri, May 22, 2015 at 11:50 AM, Vinh Quốc Nguyễn <notifications@github.com

**Comment by kureikain** [comment]
Yes,

Here is what I do:


```
Gem::Specification.new "samson_hipchat", "0.0.0" do |s|
  s.summary = "Samson hipchat integration"
  s.authors = ["Vinh Nguyen"]
  s.add_runtime_dependency "hipchat", "~> 1.5"
  s.files = `git ls-files`.split("\n")
end
```

s.files is important because we are distributing file via Gem.

Then in Gemfile:

```
gem 'samson_hipchat', require: false
```

And I have to include this patch: https://github.com/zendesk/samson/pull/418

That's all I need to make my hipchat plugin works (slack clone btw).

I think Samson should go in this direction so we can distributed plugin as gem.

**Comment by kureikain** [comment]
cc @grosser

**Comment by grosser** [comment]
Glad to see someone use this, what did you do for testing ?

Can you make a PR to add the plugin to the readme ?

On Fri, May 22, 2015 at 12:52 PM, Vinh Quốc Nguyễn <notifications@github.com

**Comment by kureikain** [comment]
> what did you do for testing ?

For testing, I'm kind of stupid.... I don't know how to test it outside of Samson environment(I'm a junor Ruby dev), so in my current dev I use sub module to pull it into `plugins` folder normally and run separate `rake test TEST=plugins/hipchat/tests/testfile.rb`

> Can you make a PR to add the plugin to the readme ?

Sure.
Will do.

**Comment by grosser** [comment]
That sounds like a kind of ugly but reliable solution :)
