### ISSUE TITLE
Hook to custom deploy form

### ISSUE THREAD

**Issue by kureikain** [zendesk/samson#463]
Hi, 

I want to custom deploy form a bit for my own purpose to add an extra friendly message (commit sometimes hard to understand).

![screen shot 2015-06-15 at 10 00 54 am](https://cloud.githubusercontent.com/assets/49754/8165477/8c6522c0-1345-11e5-8b34-64868bdfe28f.png)

I tried to find if we have any hooks for it but looks like we don't. I think what should add extra hook:

  * before_deploy_form
  * after_deploy_form 

around this block https://github.com/zendesk/samson/blob/master/app/views/deploys/new.html.erb#L21-L32 to help user custom extra view for it.

Is this something you guys consider should be added? If so, I can submit my PR. Right now I maintain my own fork which is very painful to keep it in sync :(. Ref: https://github.com/kureikain/samson/tree/deploy_form_hook

Let me know and I will clean it up, add test and submit a PR.

**Comment by sandlerr** [comment]
Please submit a PR, looks like a good feature!

**Comment by sandlerr** [comment]
this looks very much like https://github.com/zendesk/samson/pull/473

**Comment by kureikain** [comment]
@sandlerr Yes, it's me trying to get this out last weekend
