### ISSUE TITLE
What is the best way to represent different tasks in same stage

### ISSUE THREAD

**Issue by kureikain** [zendesk/samson#483]
Hi,

@grosser @sandlerr 

Assume we have a stage: Production. Inside it we have many tasks:

- Deploy
- Rollback
- Migration(We don't want to run migration inside deploy)
....

Right now I don't know how to put those things separately so that somebody can just click a single "Deploy" button and it does the job(without manually selecting command to run)

I did this in a ugly way: I created many stage:
- Production deploy
- Production rollback

Which is ugly :(.

I wonder how zendeck organize different tasks inside a stage. Do you guy use a primary command that run official deploy and macro/job to run other command (rollback for example)?

**Comment by grosser** [comment]
We never rollback, just deploy an older version ... migrations are done by a different flow ...
But I get that it's weird to deal with different tasks ... first I'd say reuse the same commands and only have the deploy/release part different ... you can use macros for these 1-off things ... but tbh I think macros are weird 1-off troublemakers :/

@zendesk/runway any good ideas for this usecase ... I guess we could have a command field and select [migrate deploy rollback] from it when deploying then use it as $COMMAND or so

**Comment by kureikain** [comment]
@grosser Thanks for answer. With your idea, I think I will make a plugin which does those thing:

- Create an extra `command_name` field in `commands` table to name each of command.
- When deploy, allow user select a dropdown list of command(show name instead of original command)

**Comment by grosser** [comment]
this sounds pretty useful to me, please ping me when it's ready ... maybe
develop it inside samson directly ...
