### ISSUE TITLE
Should not need GitHub personal access token with organization OAuth

### ISSUE THREAD

**Issue by jeffbyrnes** [zendesk/samson#51]
Perhaps I'm missing something, but my understanding is that you should need _either_ a GitHub personal access token _or_ an organization-based OAuth (the client ID & secret). Both the [README](https://github.com/zendesk/samson/blob/9ff98dea6b1c2729d4951d0286539883f9535d74/README.md#github-token-mandatory) and the app itself (by way of not working properly) seem to require both.

Would it not make more sense to do either one (depending on individual vs. org), and, if its an org-level OAuth, request all the necessary permissions upon authenticating?

**Comment by jeffbyrnes** [comment]
@steved what was the resolution on this? If the answer is “we didn’t change anything”, that’s alright, just want to know where Samson stands. Thanks!

**Comment by steved** [comment]
As far as I can find, GitHub doesn't support dynamically created organization tokens. Until they do, this won't be solvable.

**Comment by jeffbyrnes** [comment]
@steved speaking from a place of some ignorance, but why not perform the necessary permissions request upon authenticating using org-level oAuth?

I.e., you enter the necessary details into Samson, which were manually created in GitHub, then go through the auth flow, having Samson request permissions from GitHub that it needs to read commit statuses, etc.

**Comment by steved** [comment]
It's just more work, really, and that token would have to be stored as a singleton in the database. Ideally, it would be done without the user ever knowing once the proper client is set up.
