### ISSUE TITLE
Dockerfile Build fails

### ISSUE THREAD

**Issue by silverbp** [zendesk/samson#527]
It fails on line 35 cause there's no REVISION folder.

**Comment by jonmoter** [comment]
It doesn't expect a directory to be there.  It's attempting to write a file named `REVISION`, with the contents of the file being the sha of the checkout.

What error are you seeing?

**Comment by jonmoter** [comment]
Oh, sorry.  I misunderstood. I thought you meant line 34-35 of [docker_builder_service.rb](https://github.com/zendesk/samson/blob/master/app/models/docker_builder_service.rb#L34), which adds a REVISION file when running `docker build`.

You mean line 35 of [Dockerfile](https://github.com/zendesk/samson/blob/master/Dockerfile#L35), right?

Yeah, we can remove that.
