### ISSUE TITLE
Small UI issue

### ISSUE THREAD

**Issue by steved** [zendesk/samson#531]
![screen shot 2015-08-04 at 5 43 13 pm](https://cloud.githubusercontent.com/assets/13248/9075921/4f85274e-3ad0-11e5-9e5d-3a3b1b12b847.png)

**Comment by henders** [comment]
You may have to spell out for me what the UI issue is? Blue vs white buttons? Too close?

**Comment by steved** [comment]
Sorry yeah, it should be have a small margin between.
