### ISSUE TITLE
Deploy wrong version

### ISSUE THREAD

**Issue by jacopocappelli1989** [zendesk/samson#537]
Hi,
i just installed Samson and it's an incredible product!
I have only one problem, definitely something wrong but I can not figure out where.
If i say to samson to deploy my app tag 1.1.1 (that exist) ad the end of deploy i have different version HEAD version.

Maybe i pass wrong parameter :branch to capistrano?

Thanks,
J

**Comment by steved** [comment]
Do you have any more information? By different HEAD version, do you mean completely different SHA? Is this only local to samson? Are you running a `git checkout` or something inside your cap scripts?
