### ISSUE TITLE
Clearing a stage's pipeline

### ISSUE THREAD

**Issue by steved** [zendesk/samson#549]
It technically isn't possible to clear a stage's pipeline if it already has one, because `stage[next_stage_ids][]` won't be passed in by the browser.

**Comment by jonmoter** [comment]
Created JIRA story: https://zendesk.atlassian.net/browse/SAMSON-187

**Comment by sandlerr** [comment]
isn't that [this](http://stackoverflow.com/questions/8929230/why-is-the-first-element-always-blank-in-my-rails-multi-select-using-an-embedde) problem?
