### ISSUE TITLE
I almost never want relative time

### ISSUE THREAD

**Issue by osheroff** [zendesk/samson#555]
![screenshot](https://www.dropbox.com/s/ivdd6cnjw6w5wy7/Screenshot%202015-09-29%2011.51.45.png?dl=1)

If I need to know the time a deploy happened, it's almost always because I'm correlating failures between my deploy and some other event.  masking this behind "2 hours ago" is not helpful.  I do understand there's an on-hover, but it's impossible to copy/paste and just generally a pain.  thoughts?

**Comment by jonmoter** [comment]
Yeah, I generally agree with you.  I find the relative time kindof annoying.

If it showed an actual time, what sort of format would you want it in? Local time or UTC?  And would you expect to be shown the time the deploy started, or the deploy completed?

**Comment by osheroff** [comment]
I *love* the local/utc toggle that Exodus' monitor pages have, but if I were to pick just one I'd do UTC, time completed.

**Comment by rikeoka** [comment]
Is this addressed by PR #778?

**Comment by osheroff** [comment]
yeah, more or less.
