### ISSUE TITLE
Restricting login

### ISSUE THREAD

**Issue by deanperry** [zendesk/samson#562]
Hey, I'm back to giving Samson a go. I can't seem to find a way to restrict who logs in. Is this feature present or would I need to build it?

**Comment by jonmoter** [comment]
Could you say more what you mean about restricting who logs in?  Do you mean you want to have a blacklist of accounts that are denied access?  Right now authentication is through OAuth, using GitHub or Google as providers.

**Comment by deanperry** [comment]
Currently when GitHub login is enabled, anyone can login and view deployments. In some cases this is a security risk so I'd like to restrict login to just me and my team

**Comment by steved** [comment]
You can specify three options for GitHub login:
https://github.com/zendesk/samson/blob/master/.env.example#L8-L10

The organization name is mandatory for the `ADMIN` and `DEPLOYER` options. If the user is not part of the organization, they will not be allowed to login. If they are, and the other options are not set, they will default to viewers. We don't have an option to block users inside the organization, but maybe you can add it here: https://github.com/zendesk/samson/blob/master/lib/omniauth/github_authorization.rb#L7-L23

**Comment by deanperry** [comment]
OK I'll take a look, thanks
