### ISSUE TITLE
Quick import of repositories

### ISSUE THREAD

**Issue by deanperry** [zendesk/samson#563]
Hey, is there a simple way of adding GitHub repositories or do I need to manually add each one? Maybe I can create a PR if this isn't currently present?

**Comment by jonmoter** [comment]
There's currently no bulk-import functionality to create multiple Projects.  It would be relatively easy to create that, if you'd like to create PR for it.

**Comment by steved** [comment]
Given a list of repositories, it should be pretty trivial to run something like this script:

```ruby
ARGF.each_line do |repo|
  repo_name = repo.strip
  Project.create!(name: repo_name, repository_url: 'git@github.com:steved/' + repo_name)
end
```

```sh
rails runner import.rb FILE
```
