### ISSUE TITLE
Stage environment variables

### ISSUE THREAD

**Issue by mblaschke** [zendesk/samson#587]
Would be great to set stage environment variables (eg. different variables for production or staging)

**Comment by HashNuke** [comment]
@mblaschke Have you tried the *"Deploy Groups"* feature? Each deploy group can have different env vars. 

You can create and manage deploy groups on a project's settings page (in the last section).

**Comment by msufa** [comment]
@mblaschke have a look [here](https://github.com/zendesk/samson/blob/master/docs/extra_features.md#environment-and-deploy-group-managing) for details.

**Comment by mblaschke** [comment]
Will try it

**Comment by mblaschke** [comment]
Would be still nice to have different ENV-vars for each stage because they're different for each project and stage :)

Alternative: Different commands (which will not shown in command list) for each project and stage.

**Comment by eZanmoto** [comment]
As a workaround, I initialise the stage-specific environment variables in a standalone command block at the top of the "Script" section for a stage. This seems to actually do away with the need for having a specific configuration section for stages, which is what I was looking for initially.

**Comment by grosser** [comment]
I think that's a good enough workaround :)
... in general we are trying to take samson into the deploy-group direction, so have more config come in via that so different stages can deploy various groups of deploy groups and get settings from there
