### ISSUE TITLE
Make releases#index faster – make fewer API calls

### ISSUE THREAD

**Issue by bquorning** [zendesk/samson#679]
Rendering the `releases/_release.html.erb` partial (on releases#index) seems to be making an API call to GitHub. Then the partial renders `releases/_info.html.erb` which in turn renders `changeset/_pulls.html.erb` which causes _two_ more calls to GitHub. Having 15 releases shown by default on releases#index, this page now makes 45 calls to the GitHub API.

Would it be possible to reduce that number?

**Comment by jonmoter** [comment]
I think the simplest fix would be to not render the `releases/_info.html.erb` partial by default, and to lazily load that by AJAX if someone clicks on the row to see more details.  That would cut down on a lot of the calls to GitHub.
