### ISSUE TITLE
Faster stages#show

### ISSUE THREAD

**Issue by bquorning** [zendesk/samson#680]
`StagesController#show` fetches an image from shields.io during the request. Why not just respond with a 302 redirect to the image, and let the browser suffer the latency penalty?

**Comment by jonmoter** [comment]
It only does that if you're making a request to `stage_name.svg`, not the normal HTML request.

But I don't know why it's making the request server-side and proxying the response. @grosser, you implemented that in bce48989; what's the rationale?

**Comment by grosser** [comment]
should be fine to redirect ...

**Comment by grosser** [comment]
https://github.com/zendesk/samson/pull/682
