### ISSUE TITLE
Do samson only support github?

### ISSUE THREAD

**Issue by eriksenonline** [zendesk/samson#710]
I have read the help files and I wonder do samson only support Github? Is it not possible to use a regular git server to fetch sources from?

**Comment by steved** [comment]
A regular Git server should work for the base job execution as it's a regular mirror+clone, it's the GitHub features we've built around it that may not work and could interfere. I haven't tested it myself, but I'd love confirmation that it does work with just Git. And if it doesn't, what specifically needs to be fixed.

**Comment by eriksenonline** [comment]
I ended up using something else. I will re-visit this later if I have the time.
