### ISSUE TITLE
Loop causes samson to spaz out

### ISSUE THREAD

**Issue by teu** [zendesk/samson#741]
Hi,

I am evaluating samson for our orgs deployment GUI. It is very impressive. 
I have set up everything via doc, running puma in development env with github authentication with sqlite as the db. 
When however wanting to run our deployment:

``` bash
bundle install
cap production-asg deploy
```

which runs on the same user/server that samson is being ran, the cli version takes ~6minutes, while samson goes crazy and just loops causing ruby to go 100% on CPU and doesn't produce a single line of log, trying to do the same thing as the CLI, strace (part, loops over and over):

```
[pid  2028] stat("packed-refs", {st_mode=S_IFREG|0664, st_size=293286, ...}) = 0
[pid  2028] lstat("./refs/remotes/e23dd25369e59e845089972933bc9c861bb6a1f8/HEAD", 0x7fffa3031270) = -1 ENOENT (No such file or directory)
```

"e23dd25369e59e845089972933bc9c861bb6a1f8" references some 2 year old pull request. No clue what samson tries to do here.

Any idea what this could be?

Thanks

**Comment by sandlerr** [comment]
Strange that there is no output at all. Sounds like possibly a corrupted git repo. `git fsck` may confirm this.

**Comment by teu** [comment]
Hi,

there are 3 dangling commits (none of which are the one described) - but still not sure why a git clone of git fetch would ever loop like this.

**Comment by sandlerr** [comment]
Hi Piotr,
I don't *think* this looks like a samson issue - samson does not attempt to read anything from the `.git` directory directly but always shells out to the git command line tool.
If you would like to see the commands being run you can take a look at the code [here](https://github.com/zendesk/samson/blob/master/app/models/git_repository.rb#L18-L26). It is essentially `git clone #{from} #{to} && git fetch -p && git checkout #{reference}`.

Are you able to do reproduce the issue by running these commands on the cli yourself?

**Comment by teu** [comment]
Hi @salamagd,

the branch is being fetched fine, bundler did run fine and the capistrano goal is being started. The problem however is there is nothing streamed to the browser (until I actually stop the deployment) so it is impossible to know what is going on.
The first step of our deployment is to again clone the repository to a different /tmp path and do stuff in capistrano created temporary folders - doesn't even get to that with samson.

Will try for a little bit longer to get this going and them move to a different deployment GUI.

Thanks for your help
