### ISSUE TITLE
"Cropped" log output

### ISSUE THREAD

**Issue by mblaschke** [zendesk/samson#742]
Output of some chars is "cropped", eg. `Play [Deployment]` will de displayed as `PLAY eployment]`

Deployment screen:
![image](https://cloud.githubusercontent.com/assets/7583579/13028898/e30d699c-d27c-11e5-963a-52a36488a8e0.png)

Plain log:
[test-production-23-20160213_1702UTC.txt](https://github.com/zendesk/samson/files/129288/test-production-23-20160213_1702UTC.txt)

Deployment is done with Ansible (Ansistrano) and just a small bash wrapper script (https://github.com/webdevops/samson-deployment/blob/develop/deployment/deploy)

**Comment by steved** [comment]
I think this is ansible (the [gem](https://github.com/tddium/ansible)) being overly greedy. Would be nice to find a better alternative.

**Comment by mblaschke** [comment]
Output is filtered inside `render_log ` of `application_helper`:

If i remove `.gsub(/\[([A-Z]|[0-9]+)m?/, '')` output is correct.

https://github.com/zendesk/samson/blob/master/app/helpers/application_helper.rb#L12
