### ISSUE TITLE
Samson should verify cached repo url when deploying, and remove cached copy when url updated

### ISSUE THREAD

**Issue by halcyonCorsair** [zendesk/samson#75]
If you update the url of a project that has a cached copy, it does not currently update the cached copy and requires manual removal of the cached copy before deployments can proceed.

To reproduce:
  1. Create a project
  1. Deploy any version so repository is cached
  1. Change repository url to something different
  1. Deploy a sha, tag, or branch not present in the original repo

Result:
![screen shot 2014-08-29 at 11 07 18 am](https://cloud.githubusercontent.com/assets/113981/4085284/f7d22d9e-2f18-11e4-9e16-65b616d5810c.png)

**Comment by grosser** [comment]
that should be fixed
