### ISSUE TITLE
Export PROJECT as variable

### ISSUE THREAD

**Issue by mblaschke** [zendesk/samson#768]
REVISION, TAG, STAGE is exported before deployment commands are executed but not the PROJECT.

Would be nice if PROJECT would be also available.

**Comment by jonmoter** [comment]
Could you add a command saying something like `export PROJECT="myprojectname"`, and add that command to each stage of your project?

**Comment by mblaschke** [comment]
`URL`, `DEPLOY_URL`, `DEPLOYER` etc are also exported per default so it would be nice to get the project name, repository url and permalink for eg. automatic chat status reporting.

We would like to add some default tasks in our [webdevops/samson-deployment service](https://github.com/webdevops/samson-deployment) (based on your docker image) eg. for slack and hipchat reporting so that the user don't need to setup any env vars :)

BTW: Thanks for the great work :)
