### ISSUE TITLE
kubernetes plugin: Use Deployments

### ISSUE THREAD

**Issue by rata** [zendesk/samson#775]
The deployment kind, in api: extensions/v1beta1, is the recommended approach now instead of replication controllers. All kubernetes add ons are moved to that, now.

Is there a plan to support deployments?

**Comment by jonmoter** [comment]
I'm able to use the deployments API, it just requires using a slightly different client.

```
deployment = Kubeclient::Deployment.new(deployment_hash)
client = Kubeclient::Client.new(cluster.server + '/apis', 'extensions/v1beta1')
client.create_deployment(deployment)
```

**Comment by rata** [comment]
Oh, thanks! I'll try that

**Comment by rata** [comment]
I can confirm I can use it, closing this!
