### ISSUE TITLE
Slack webhook fields not showing in stage edit form

### ISSUE THREAD

**Issue by michael-bouvy** [zendesk/samson#837]
Hi,

When creating or editing a stage, Slack webhook fields (URL and Channel) are only visible if at least 1 webhook exists for the stage.

Although I'm not a Ruby developper, I got the expected behavior by changing line `5` in `plugins/slack_webhooks/app/views/samson_slack_webhooks/_fields.html.erb` from:

```rb
<% stage.slack_webhooks.build unless stage.slack_webhooks.last.try(:webhook_url).blank? %>
```

to:

```rb
<% stage.slack_webhooks.build %>
```

I'm wondering if it is the correct way of fixing this. If yes, I'd be pleased submitting a PR. 👍 

Expected behavior in image:

![image](https://cloud.githubusercontent.com/assets/1674029/14588597/6ef97248-04cd-11e6-9465-6e2872143199.png)

**Comment by grosser** [comment]
Yes it's a bug, but the intention was that it should not show a new row
when the last row was empty, so the correct fix would be:

stage.slack_webhooks.build if (last = stage.slack_webhooks.last) &&
last.webhook_url.blank?

please open a PR!

if you feel funky, try adding a test too `it "shows a form when no webhook
exists"`

**Comment by michael-bouvy** [comment]
Thanks for your quick reply!

How could the last row be empty? I tried adding a webhook with only the channel set, but it is not saved.

Will try to write a test 😎

**Comment by grosser** [comment]
maybe when trying to save and it fails the same form is re-rendered ... or
something like that ... if it does not work, then feel free to just use
.build without conditions

**Comment by michael-bouvy** [comment]
Ok. Could you just advise me how to get started with the test? I looked at existing ones but could not find something equivalent.

**Comment by grosser** [comment]
https://github.com/zendesk/samson/blob/master/test/controllers/admin/secrets_controller_test.rb#L34
