### ISSUE TITLE
Use git worktree instead of cloning cached repos

### ISSUE THREAD

**Issue by mariovisic** [zendesk/samson#943]
Hi team

I'd like to propose using `git worktree` in place of the current system where each time a job is created the cached repo is cloned to a temporary directory. There would be a number of benefits of swapping this over.

Git worktree works by creating a copy of the project folder but symlinking a lot of the git internals, this means that it can see the exact same tree as the cached repo, if you fetch on the cached repo for example the worktree will also see it but they can point to different HEADs. It's as simple as `git worktree add /tmp/path <ref> --force` Then once  the folder is removed simply `git worktree prune`.

Git worktrees are much quicker than cloning, here is a benchmark on a fairly large repo:

```
$ time git clone project project-temp
Cloning into 'project-temp'...
done.
Checking out files: 100% (12544/12544), done.

real	0m9.838s
user	0m0.856s
sys	0m3.351s

$ time git worktree add ../project-temp master --force
Preparing ../project-temp (identifier project-temp)
HEAD is now at b2c6367 Merge pull request #16000 from envato/analytics_constant_resolution

real	0m3.147s
user	0m0.734s
sys	0m1.513s
```

Ir also takes much less space as all of the git objects are symlinked.

```
# with clone
$ du -sh project-temp/
1.7G	project-temp/

# with worktree
$ du -sh project-temp/
239M	project-temp/
```

The code changes should be fairly minimal, only a change to `GitRepository#setup!` would be required and a small amount of connecting parts.

Thoughts?

**Comment by grosser** [comment]
yes please!

**Comment by mariovisic** [comment]
See #944
