### ISSUE TITLE
Kubernetes deployment yaml with several containers fails

### ISSUE THREAD

**Issue by rata** [zendesk/samson#966]
Hi,

All of our pods use several containers. Right now, we were making sure the first container was the one we changed on release and the other were "helper containers" (log collector, etc.), so a release of the app does not affect those typically.

But now, since https://github.com/zendesk/samson/pull/945/files, there is a validation and we can't deploy anymore our kubernetes pods. Is there any reason for that? Can't it just be the first but not fail if there are more containers in the pod?

Thanks!
Rodrigo

**Comment by grosser** [comment]
Reason for adding that was to prevent the silent ignore of multiple
containers ... can we somehow properly support multiple containers ?

**Comment by jonmoter** [comment]
Ah yes. Right, we do need to support multiple containers in a Pod, so we can do sidecar containers.

@grosser, let's remove that check that there's exactly one container.  We don't yet have a way to modify multiple containers as part of a deployment, so the other container specs will remain untouched.

**Comment by grosser** [comment]
Sounds good.
So atm the other Containers are not getting built but are still deployed
right ?

**Comment by jonmoter** [comment]
Right. So they might point to something like `busybox:latest` rather than a specific digest. That's probably something we'll need to solve for security reasons at Zendesk, but is a reasonable use case elsewhere.

**Comment by rata** [comment]
@jonmoter @grosser yeap, doing just that should work for us! Great there is no big reason to not support them :-D

**Comment by rata** [comment]
@jonmoter @grosser Should I do a PR just deleting the validation? (and update the tests)

**Comment by grosser** [comment]
I'll do the PR

**Comment by rata** [comment]
@grosser thanks!

**Comment by grosser** [comment]
https://github.com/zendesk/samson/pull/968

**Comment by rata** [comment]
@grosser was this overwritten with a forced push? I don't see it merged in master

**Comment by grosser** [comment]
was not merged yet, now it is

**Comment by rata** [comment]
Oh, sorry, follow the wrong link I think. Sorry for the noise, really :-/
