### ISSUE TITLE
assets precompile broken

### ISSUE THREAD

**Issue by rata** [zendesk/samson#991]
Hi,

@grosser, it seems the last merge broke the assets precompile. It's late here (8:40PM), so I can't look at it now.

But here is the log just in case:

```
Step 10 : RUN rake assets:precompile
 ---> Running in 477ad5dcf69e
/usr/local/bundle/bin/rake: No such file or directory - git
rake aborted!
NoMethodError: undefined method `chomp' for nil:NilClass
/app/config/initializers/revision.rb:6:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'

```

**Comment by grosser** [comment]
Needs either of these to work:
 - `REVISION` file in root
 - `HEROKU_SLUG_COMMIT` env variable set
 - a `git` checkout

**Comment by grosser** [comment]
basically there is no git installed now .. so samson is unusable anyway ?

**Comment by sandlerr** [comment]
@grosser none of these conditions are met by the docker image as it stands. I've just been adding HEROKU_SLUG_COMMIT=fafafaf when I need to use it - is there a correct way here?

**Comment by rata** [comment]
On Mon, May 16, 2016 at 04:47:45PM -0700, Michael Grosser wrote:
> basically there is no git installed now .. so samson is unusable anyway ?

The docker image, at least.

**Comment by grosser** [comment]
Add git ... ?

**Comment by sandlerr** [comment]
I don't think adding git solves this problem. The docker image doesn't contain the .git directory

**Comment by grosser** [comment]
it solves the issue since `git xxx` no longer blows up ... it would fail and generate some weird output, but it won't crash / will only be noticeable in the UI ... so merging your PR kind of solved this issue ;)

**Comment by rata** [comment]
This is fixed now, thanks!
